Repository Azure/ResourceModules, pull requests merged in 2021-11, with the labels that each got.

#350 + additional ER GW Skus to support no AZ regions
  arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
Labels: bug

#345 Key vault restructured
  .github/workflows/ms.keyvault.vaults.yml
  .github/workflows/scripts/Set-ModuleReadMe.ps1
  arm/.global/global.module.tests.ps1
  arm/Microsoft.KeyVault/vaults/.bicep/nested_rbac.bicep
  arm/Microsoft.KeyVault/vaults/.parameters/min.parameters.json
  arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/.bicep/nested_cuaId.bicep
  arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.KeyVault/vaults/secrets/.bicep/nested_cuaId.bicep
  arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
  arm/Microsoft.KeyVault/vaults/secrets/readme.md
Labels: enhancement

#317 Sql server restructured
  .github/workflows/ms.sql.servers.databases.yml
  arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
  arm/Microsoft.Sql/servers/.bicep/nested_rbac.bicep
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/databases/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/servers/databases/deploy.bicep
  arm/Microsoft.Sql/servers/databases/readme.md
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/readme.md
  arm/Microsoft.Sql/serversResources/databases/.parameters/parameters.json
Labels: enhancement

#420 Cleaned up network modules & added output descriptions
  arm/Microsoft.Network/applicationGateways/deploy.bicep
  arm/Microsoft.Network/applicationGateways/readme.md
  arm/Microsoft.Network/applicationSecurityGroups/deploy.bicep
  arm/Microsoft.Network/applicationSecurityGroups/readme.md
  arm/Microsoft.Network/azureFirewalls/deploy.bicep
  arm/Microsoft.Network/azureFirewalls/readme.md
  arm/Microsoft.Network/bastionHosts/deploy.bicep
  arm/Microsoft.Network/bastionHosts/readme.md
  arm/Microsoft.Network/connections/deploy.bicep
  arm/Microsoft.Network/connections/readme.md
  arm/Microsoft.Network/ddosProtectionPlans/deploy.bicep
  arm/Microsoft.Network/ddosProtectionPlans/readme.md
  arm/Microsoft.Network/expressRouteCircuits/deploy.bicep
  arm/Microsoft.Network/expressRouteCircuits/readme.md
  arm/Microsoft.Network/ipGroups/deploy.bicep
  arm/Microsoft.Network/ipGroups/readme.md
  arm/Microsoft.Network/loadBalancers/deploy.bicep
  arm/Microsoft.Network/loadBalancers/readme.md
  arm/Microsoft.Network/localNetworkGateways/deploy.bicep
  arm/Microsoft.Network/localNetworkGateways/readme.md
  arm/Microsoft.Network/natGateways/deploy.bicep
  arm/Microsoft.Network/natGateways/readme.md
  arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/readme.md
  arm/Microsoft.Network/networkWatcherFlowLogs/deploy.bicep
  arm/Microsoft.Network/networkWatcherFlowLogs/readme.md
  arm/Microsoft.Network/networkWatchers/deploy.bicep
  arm/Microsoft.Network/networkWatchers/readme.md
  arm/Microsoft.Network/privateDnsZones/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/readme.md
  arm/Microsoft.Network/privateEndpoints/deploy.bicep
  arm/Microsoft.Network/privateEndpoints/readme.md
  arm/Microsoft.Network/publicIPAddresses/deploy.bicep
  arm/Microsoft.Network/publicIPAddresses/readme.md
  arm/Microsoft.Network/publicIPPrefixes/deploy.bicep
  arm/Microsoft.Network/publicIPPrefixes/readme.md
  arm/Microsoft.Network/routeTables/deploy.bicep
  arm/Microsoft.Network/routeTables/readme.md
  arm/Microsoft.Network/trafficmanagerprofiles/deploy.bicep
  arm/Microsoft.Network/trafficmanagerprofiles/readme.md
  arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
  arm/Microsoft.Network/virtualNetworkGateways/readme.md
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/readme.md
  arm/Microsoft.Network/virtualWans/deploy.bicep
  arm/Microsoft.Network/virtualWans/readme.md
Labels: enhancement, [cat] modules

#423 Cleaned up service bus module & added output descriptions
  arm/Microsoft.ServiceBus/namespaces/.bicep/nested_privateEndpoints.bicep
  arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
  arm/Microsoft.ServiceBus/namespaces/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/queues/.bicep/nested_rbac.bicep
  arm/Microsoft.ServiceBus/namespaces/queues/deploy.bicep
Labels: enhancement, [cat] modules

#424 Cleaned up api management modules & added output descriptions
  arm/Microsoft.ApiManagement/service/deploy.bicep
  arm/Microsoft.ApiManagement/service/readme.md
  arm/Microsoft.ApiManagement/serviceResources/apis/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/apis/readme.md
  arm/Microsoft.ApiManagement/serviceResources/authorizationServers/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/authorizationServers/readme.md
  arm/Microsoft.ApiManagement/serviceResources/backends/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/backends/readme.md
  arm/Microsoft.ApiManagement/serviceResources/caches/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/caches/readme.md
  arm/Microsoft.ApiManagement/serviceResources/namedValues/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/namedValues/readme.md
  arm/Microsoft.ApiManagement/serviceResources/products/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/products/readme.md
  arm/Microsoft.ApiManagement/serviceResources/subscriptions/deploy.bicep
  arm/Microsoft.ApiManagement/serviceResources/subscriptions/readme.md
Labels: enhancement, [cat] modules

#422 Cleaned up web modules & added output descriptions
  arm/Microsoft.Web/connections/deploy.bicep
  arm/Microsoft.Web/connections/readme.md
  arm/Microsoft.Web/hostingEnvironments/deploy.bicep
  arm/Microsoft.Web/hostingEnvironments/readme.md
  arm/Microsoft.Web/serverfarms/deploy.bicep
  arm/Microsoft.Web/serverfarms/readme.md
  arm/Microsoft.Web/sites/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Web/sites/deploy.bicep
  arm/Microsoft.Web/sites/readme.md
Labels: enhancement, [cat] modules

#421 Cleaned up compute modules & added output descriptions
  arm/Microsoft.Compute/availabilitySets/deploy.bicep
  arm/Microsoft.Compute/availabilitySets/readme.md
  arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
  arm/Microsoft.Compute/diskEncryptionSets/readme.md
  arm/Microsoft.Compute/images/deploy.bicep
  arm/Microsoft.Compute/images/readme.md
  arm/Microsoft.Compute/proximityPlacementGroups/deploy.bicep
  arm/Microsoft.Compute/proximityPlacementGroups/readme.md
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_extension.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
Labels: enhancement, [cat] modules

#407 Restructured EventHub to new child-resources structure
  .github/workflows/ms.eventhub.namespaces.yml
  .github/workflows/platform.updateReadMe.yml
  arm/Microsoft.EventHub/namespaces/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.EventHub/namespaces/.parameters/min.parameters.json
  arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
  arm/Microsoft.EventHub/namespaces/authorizationRules/.bicep/nested_cuaId.bicep
  arm/Microsoft.EventHub/namespaces/authorizationRules/deploy.bicep
  arm/Microsoft.EventHub/namespaces/authorizationRules/readme.md
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/.bicep/nested_cuaId.bicep
  arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/deploy.bicep
  arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/readme.md
  arm/Microsoft.EventHub/namespaces/eventhubs/.bicep/nested_cuaId.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/.bicep/nested_rbac.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/.bicep/nested_cuaId.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/readme.md
  arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/.bicep/nested_cuaId.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/readme.md
  arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/readme.md
  arm/Microsoft.EventHub/namespaces/readme.md
  arm/Microsoft.EventHub/namespacesResources/eventhubs/.parameters/parameters.json
  arm/Microsoft.EventHub/namespacesResources/eventhubs/deploy.bicep
  utilities/tools/Set-GitHubReadMeModuleTable.ps1
  utilities/tools/helper/Get-ModulesAsMarkdownTable.ps1
  utilities/tools/helper/Merge-FileWithNewContent.ps1
Labels: enhancement, [cat] modules

#429 Removed unsupported default value
  .github/actions/templates/publishModule/action.yml
  .github/actions/templates/validateModuleApis/action.yml
  .github/actions/templates/validateModuleGeneral/action.yml
Labels: bug, [cat] pipelines

#405 Users/torivara/virtual network gateways update
  arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
  arm/Microsoft.Network/virtualNetworkGateways/readme.md
Labels: bug, [cat] modules

#433 Hotfix for Azure Policy Exemptions. Updated Policy Assignment ID and extended date
  arm/Microsoft.Authorization/policyExemptions/.parameters/parameters.json
Labels: bug, [cat] pipelines

#448 Update Dependency pipeline after child restructure
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  utilities/dependencies/Microsoft.EventHub/namespaces/parameters/parameters.json
  utilities/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
  utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/2.vnetpeer01.parameters.json
  utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/3.vnetpeer02.parameters.json
  utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/4.azfw.parameters.json
  utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/5.aks.parameters.json
  utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/6.sqlmi.parameters.json
  utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/parameters.json
Labels: bug, enhancement, [cat] pipelines, [cat] modules, [cat] testing

#412 Closes #340: Update AVD Application groups
  .github/workflows/ms.desktopvirtualization.applicationgroups.applications.yml
  .github/workflows/ms.desktopvirtualization.applicationgroups.yml
  arm/Microsoft.DesktopVirtualization/applicationGroupsResources/applications/.parameters/parameters.json
  arm/Microsoft.DesktopVirtualization/applicationGroupsResources/applications/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationGroupsResources/applications/readme.md
  arm/Microsoft.DesktopVirtualization/applicationgroups/.parameters/min.parameters.json
  arm/Microsoft.DesktopVirtualization/applicationgroups/.parameters/parameters.json
  arm/Microsoft.DesktopVirtualization/applicationgroups/applications/.bicep/nested_cuaId.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/applications/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/applications/readme.md
  arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/readme.md
Labels: [prio] high, [cat] modules

#460 Users/ahmad/dependency avd
  utilities/dependencies/Microsoft.DesktopVirtualization/applicationgroups/parameters/parameters.json
Labels: bug

#447 Tokens Replacement Service [Pilot]
  .github/actions/sharedScripts/Convert-TokensInFiles.ps1
  .github/actions/sharedScripts/Set-EnvironmentOnAgent.ps1
  .github/actions/templates/deployModule/action.yml
  .github/actions/templates/validateModuleDeploy/action.yml
  .github/workflows/ms.network.applicationsecuritygroups.yml
  .github/workflows/ms.network.networksecuritygroups.yml
  .github/workflows/ms.storage.storageaccounts.yml
  .github/workflows/platform.dependencies.yml
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Network/applicationSecurityGroups/.parameters/parameters.json
  arm/Microsoft.Network/networkSecurityGroups/.parameters/parameters.json
  arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
  docs/media/paramFileTokenGetTokens.jpg
  docs/media/paramFileTokenSetKeyVault.jpg
  docs/wiki/GettingStarted.md
  docs/wiki/Modules.md
  docs/wiki/ParameterFileTokens.md
  docs/wiki/PipelinesDesign.md
  docs/wiki/TestingDesign.md
  docs/wiki/TestingUsage.md
  settings.json
  utilities/dependencies/Microsoft.KeyVault/vaults/parameters/platform.parameters.json
  utilities/dependencies/Microsoft.Resources/resourceGroups/parameters/platform-core.parameters.json
  utilities/tokensReplacement/Convert-TokensInParameterFile.ps1
  utilities/tokensReplacement/Set-LocalCustomParameterFileTokensInKeyVault.ps1
  utilities/tokensReplacement/helper/Convert-TokensInFileList.ps1
  utilities/tokensReplacement/helper/Get-RemoteCustomParameterFileTokens.ps1
  utilities/tools/Test-ModuleLocally.ps1
Labels: documentation, [prio] high, [cat] pipelines

#467 Microsoft.Automation\automationAccounts refactoring
  .github/workflows/ms.automation.automationaccounts.yml
  arm/Microsoft.Automation/automationAccounts/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Automation/automationAccounts/.bicep/nested_rbac.bicep
  arm/Microsoft.Automation/automationAccounts/.parameters/min.parameters.json
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/jobSchedules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Automation/automationAccounts/jobSchedules/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/jobSchedules/readme.md
  arm/Microsoft.Automation/automationAccounts/modules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Automation/automationAccounts/modules/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/modules/readme.md
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.Automation/automationAccounts/runbooks/.bicep/nested_cuaId.bicep
  arm/Microsoft.Automation/automationAccounts/runbooks/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/runbooks/readme.md
  arm/Microsoft.Automation/automationAccounts/schedules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Automation/automationAccounts/schedules/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/schedules/readme.md
Labels: [prio] high, [cat] modules

#471 Users/alsehr/simoneb ms removal
  .github/workflows/ms.netapp.netappaccounts.yml
  utilities/resourceRemoval/Remove-DeployedModule.ps1
  utilities/resourceRemoval/Remove-NetAppAccount.ps1
  utilities/resourceRemoval/Remove-vWan.ps1
  utilities/resourceRemoval/helper/Remove-Resource.ps1
Labels: [cat] pipelines

#483 Closes #347: Virtual Machine Module Refactor
  .github/workflows/ms.compute.virtualmachines.yml
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_extension.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress_rbac.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_rbac.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_rbac.bicep
  arm/Microsoft.Compute/virtualMachines/.parameters/min.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/parameters.json
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/extensions/.bicep/nested_cuaId.bicep
  arm/Microsoft.Compute/virtualMachines/extensions/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/extensions/readme.md
  arm/Microsoft.Compute/virtualMachines/readme.md
Labels: enhancement, [cat] modules

#491 add missing keyword Optional
  arm/Microsoft.ServiceBus/namespaces/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/readme.md
Labels: bug

#488 Closes: #487 - Fixed Test-ModuleLocally Script Post Folder Restructures + Updated Links in Wiki
  docs/wiki/ParameterFileTokens.md
  utilities/tools/Test-ModuleLocally.ps1
Labels: bug, documentation, [cat] testing

#477 Dependency pipeline update
  .github/workflows/platform.dependencies.yml
  docs/wiki/TestingDesign.md
  utilities/pipelines/dependencies/Microsoft.ApiManagement/service/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Automation/automationAccounts/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.EventHub/namespacesResources/eventhubs/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/law.parameters.json
Labels: documentation, enhancement, [cat] testing

#499 Users/alsehr/storage account child
  arm/Microsoft.Sql/managedInstances/.bicep/nested_rbac.bicep
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/.bicep/nested_rbac.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/.bicep/nested_rbac.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/readme.md
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/deploy.json
  arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/.bicep/nested_rbac.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
  arm/Microsoft.Storage/storageAccounts/managementPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.Storage/storageAccounts/managementPolicies/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/managementPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/.bicep/nested_rbac.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/readme.md
  arm/Microsoft.Storage/storageAccounts/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/tables/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/tables/readme.md
  utilities/tools/Test-ModuleLocally.ps1
Labels: enhancement, [cat] modules

#511 Hofix Microsoft.ContainerService agentPools Bugfix
  arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
  arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
Labels: bug

#322 Managed instance restructured
  .github/workflows/ms.sql.managedinstances.databases.yml
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Sql/managedInstances/.parameters/parameters.json
  arm/Microsoft.Sql/managedInstances/administrators/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/administrators/deploy.bicep
  arm/Microsoft.Sql/managedInstances/administrators/readme.md
  arm/Microsoft.Sql/managedInstances/databases/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/readme.md
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/readme.md
  arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/readme.md
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Sql/managedInstances/encryptionProtector/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/encryptionProtector/deploy.bicep
  arm/Microsoft.Sql/managedInstances/encryptionProtector/readme.md
  arm/Microsoft.Sql/managedInstances/keys/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/keys/deploy.bicep
  arm/Microsoft.Sql/managedInstances/keys/readme.md
  arm/Microsoft.Sql/managedInstances/readme.md
  arm/Microsoft.Sql/managedInstances/securityAlertPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/securityAlertPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/securityAlertPolicies/readme.md
  arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/deploy.bicep
  arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/readme.md
  arm/Microsoft.Sql/managedInstancesResources/databases/.parameters/parameters.json
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  utilities/tools/Set-ModuleReadMe.ps1
  utilities/tools/Test-ModuleLocally.ps1
Labels: enhancement, [cat] modules

#533 Move SQL Server database childs into correct structure
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/firewallRules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/servers/firewallRules/deploy.bicep
  arm/Microsoft.Sql/servers/firewallRules/readme.md
  arm/Microsoft.Sql/servers/readme.md
  arm/Microsoft.Sql/servers/securityAlertPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
  arm/Microsoft.Sql/servers/securityAlertPolicies/readme.md
Labels: [cat] modules

#495 Users/yimengyuan/privatednsrefactored
  arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
  arm/Microsoft.Network/privateDnsZones/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/readme.md
  arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/readme.md
Labels: enhancement, [prio] high, [cat] modules

#584 Hotfix - Private DNS Zone Name was using Token
  arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
Labels: bug

#590 Refactored RSV to use `existing`
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/readme.md
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
  arm/Microsoft.RecoveryServices/vaults/readme.md
Labels: enhancement, [cat] modules

#594 Updated inputs, outputs & readme
  arm/Microsoft.ManagedIdentity/userAssignedIdentities/.parameters/parameters.json
  arm/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
  arm/Microsoft.ManagedIdentity/userAssignedIdentities/readme.md
  utilities/pipelines/dependencies/Microsoft.ManagedIdentity/userAssignedIdentities/parameters/parameters.json
Labels: enhancement, [cat] modules

#593 Updated inputs, outputs & readMe
  arm/Microsoft.Logic/workflows/.parameters/parameters.json
  arm/Microsoft.Logic/workflows/deploy.bicep
  arm/Microsoft.Logic/workflows/readme.md
Labels: enhancement, [cat] modules

#595 Update inputs, outputs & readme
  arm/Microsoft.Management/managementGroups/.bicep/nested_rbac.bicep
  arm/Microsoft.Management/managementGroups/.parameters/parameters.json
  arm/Microsoft.Management/managementGroups/deploy.bicep
  arm/Microsoft.Management/managementGroups/readme.md
Labels: enhancement, [cat] modules

#586 Updated resources namespace to naming pattern
  arm/Microsoft.Resources/deploymentScripts/.parameters/parameters.json
  arm/Microsoft.Resources/deploymentScripts/deploy.bicep
  arm/Microsoft.Resources/deploymentScripts/readme.md
  arm/Microsoft.Resources/resourceGroups/.parameters/parameters.json
  arm/Microsoft.Resources/resourceGroups/deploy.bicep
  arm/Microsoft.Resources/resourceGroups/readme.md
  utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/artifacts.parameters.json
  utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/platform-core.parameters.json
  utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/validation.parameters.json
Labels: documentation, enhancement, [cat] modules

#597 Update inputs, outputs & readme
  arm/Microsoft.Insights/actionGroups/.parameters/parameters.json
  arm/Microsoft.Insights/actionGroups/deploy.bicep
  arm/Microsoft.Insights/actionGroups/readme.md
  arm/Microsoft.Insights/activityLogAlerts/.parameters/parameters.json
  arm/Microsoft.Insights/activityLogAlerts/deploy.bicep
  arm/Microsoft.Insights/activityLogAlerts/readme.md
  arm/Microsoft.Insights/components/.parameters/parameters.json
  arm/Microsoft.Insights/components/deploy.bicep
  arm/Microsoft.Insights/components/readme.md
  arm/Microsoft.Insights/diagnosticSettings/.parameters/parameters.json
  arm/Microsoft.Insights/diagnosticSettings/deploy.bicep
  arm/Microsoft.Insights/diagnosticSettings/readme.md
  arm/Microsoft.Insights/metricAlerts/.parameters/parameters.json
  arm/Microsoft.Insights/metricAlerts/deploy.bicep
  arm/Microsoft.Insights/metricAlerts/readme.md
  arm/Microsoft.Insights/privateLinkScopes/.parameters/parameters.json
  arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
  arm/Microsoft.Insights/privateLinkScopes/readme.md
  arm/Microsoft.Insights/scheduledQueryRules/deploy.bicep
  arm/Microsoft.Insights/scheduledQueryRules/readme.md
  utilities/pipelines/dependencies/Microsoft.Insights/actionGroups/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Insights/components/parameters/parameters.json
Labels: documentation, [cat] modules

#592 Update the inputs, outputs und docs
  arm/Microsoft.ManagedServices/registrationDefinitions/.parameters/parameters.json
  arm/Microsoft.ManagedServices/registrationDefinitions/.parameters/rg.parameters.json
  arm/Microsoft.ManagedServices/registrationDefinitions/deploy.bicep
  arm/Microsoft.ManagedServices/registrationDefinitions/readme.md
Labels: enhancement, [cat] modules

#619 Update API with `existing`
  arm/Microsoft.ApiManagement/service/apiVersionSets/deploy.bicep
  arm/Microsoft.ApiManagement/service/apiVersionSets/readme.md
  arm/Microsoft.ApiManagement/service/apis/deploy.bicep
  arm/Microsoft.ApiManagement/service/apis/policies/deploy.bicep
  arm/Microsoft.ApiManagement/service/apis/policies/readme.md
  arm/Microsoft.ApiManagement/service/apis/readme.md
  arm/Microsoft.ApiManagement/service/authorizationServers/deploy.bicep
  arm/Microsoft.ApiManagement/service/authorizationServers/readme.md
  arm/Microsoft.ApiManagement/service/backends/deploy.bicep
  arm/Microsoft.ApiManagement/service/backends/readme.md
  arm/Microsoft.ApiManagement/service/caches/deploy.bicep
  arm/Microsoft.ApiManagement/service/caches/readme.md
  arm/Microsoft.ApiManagement/service/identityProviders/deploy.bicep
  arm/Microsoft.ApiManagement/service/identityProviders/readme.md
  arm/Microsoft.ApiManagement/service/namedValues/deploy.bicep
  arm/Microsoft.ApiManagement/service/namedValues/readme.md
  arm/Microsoft.ApiManagement/service/policies/deploy.bicep
  arm/Microsoft.ApiManagement/service/policies/readme.md
  arm/Microsoft.ApiManagement/service/portalsettings/deploy.bicep
  arm/Microsoft.ApiManagement/service/portalsettings/readme.md
  arm/Microsoft.ApiManagement/service/products/apis/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/apis/readme.md
  arm/Microsoft.ApiManagement/service/products/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/groups/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/groups/readme.md
  arm/Microsoft.ApiManagement/service/products/readme.md
  arm/Microsoft.ApiManagement/service/readme.md
  arm/Microsoft.ApiManagement/service/subscriptions/deploy.bicep
  arm/Microsoft.ApiManagement/service/subscriptions/readme.md
Labels: enhancement, [cat] modules

#618 Updated Analysis Services to use `name` input parameter
  arm/Microsoft.AnalysisServices/servers/.parameters/min.parameters.json
  arm/Microsoft.AnalysisServices/servers/.parameters/parameters.json
  arm/Microsoft.AnalysisServices/servers/deploy.bicep
  arm/Microsoft.AnalysisServices/servers/readme.md
Labels: enhancement, [cat] modules

#617 Update ImageTemplate to use `name` input parameter
  arm/Microsoft.VirtualMachineImages/imageTemplates/.parameters/parameters.json
  arm/Microsoft.VirtualMachineImages/imageTemplates/deploy.bicep
  arm/Microsoft.VirtualMachineImages/imageTemplates/readme.md
Labels: enhancement, [cat] modules

#615 Updated batch to use `name` input parameter
  arm/Microsoft.Batch/batchAccounts/.parameters/parameters.json
  arm/Microsoft.Batch/batchAccounts/deploy.bicep
  arm/Microsoft.Batch/batchAccounts/readme.md
Labels: enhancement, [cat] modules

#614 Updated cognitive services to use `name` input parameter
  arm/Microsoft.CognitiveServices/accounts/.parameters/parameters.json
  arm/Microsoft.CognitiveServices/accounts/deploy.bicep
  arm/Microsoft.CognitiveServices/accounts/readme.md
Labels: enhancement, [cat] modules

#613 Update budget to use `name` input parameter
  arm/Microsoft.Consumption/budgets/deploy.bicep
  arm/Microsoft.Consumption/budgets/readme.md
Labels: enhancement, [cat] modules

#612 Update ContainerInstance to use `name` input parameter
  arm/Microsoft.ContainerInstance/containerGroups/.parameters/parameters.json
  arm/Microsoft.ContainerInstance/containerGroups/deploy.bicep
  arm/Microsoft.ContainerInstance/containerGroups/readme.md
Labels: enhancement, [cat] modules

#611 Updata Databricks to use `name` input param
  arm/Microsoft.Databricks/workspaces/.parameters/parameters.json
  arm/Microsoft.Databricks/workspaces/deploy.bicep
  arm/Microsoft.Databricks/workspaces/readme.md
Labels: enhancement, [cat] modules

#610 Updated DataFactory to use `existing`
  arm/Microsoft.DataFactory/factories/integrationRuntime/deploy.bicep
  arm/Microsoft.DataFactory/factories/integrationRuntime/readme.md
  arm/Microsoft.DataFactory/factories/managedVirtualNetwork/deploy.bicep
  arm/Microsoft.DataFactory/factories/managedVirtualNetwork/readme.md
  arm/Microsoft.DataFactory/factories/readme.md
Labels: enhancement, [cat] modules

#609 Updated ManagedClusters to use `existing`
  arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
  arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
  arm/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
Labels: enhancement

#607 Updated DocumentDB to use `existing`
  arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/readme.md
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/readme.md
  arm/Microsoft.DocumentDB/databaseAccounts/readme.md
  arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readme.md
  arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/readme.md
Labels: enhancement, [cat] modules

#606 Update to latest
  arm/Microsoft.EventGrid/topics/.parameters/parameters.json
  arm/Microsoft.EventGrid/topics/deploy.bicep
  arm/Microsoft.EventGrid/topics/readme.md
Labels: enhancement, [cat] modules

#605 Update EventHub to use `existing`
  arm/Microsoft.EventHub/namespaces/authorizationRules/deploy.bicep
  arm/Microsoft.EventHub/namespaces/authorizationRules/readme.md
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/deploy.bicep
  arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/readme.md
  arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/readme.md
  arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/readme.md
  arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/readme.md
  arm/Microsoft.EventHub/namespaces/readme.md
Labels: enhancement, [cat] modules

#604 Update input parameter to `name`
  arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
  arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
Labels: enhancement, [cat] modules

#603 Updated AVD namespace to use `existing`
  arm/Microsoft.DesktopVirtualization/applicationgroups/applications/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/readme.md
  arm/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
  arm/Microsoft.DesktopVirtualization/hostpools/readme.md
  arm/Microsoft.DesktopVirtualization/workspaces/deploy.bicep
  arm/Microsoft.DesktopVirtualization/workspaces/readme.md
Labels: documentation, enhancement, [cat] modules

#591 Updated OMS to use `existing`
  arm/Microsoft.OperationalInsights/workspaces/.parameters/min.parameters.json
  arm/Microsoft.OperationalInsights/workspaces/.parameters/parameters.json
  arm/Microsoft.OperationalInsights/workspaces/dataSources/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/dataSources/readme.md
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/linkedServices/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/linkedServices/readme.md
  arm/Microsoft.OperationalInsights/workspaces/readme.md
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/readme.md
  utilities/pipelines/dependencies/Microsoft.OperationalInsights/workspaces/parameters/parameters.json
Labels: enhancement, [cat] modules

#587 Updated Microsoft.SQL to child-resource structure
  arm/Microsoft.Sql/managedInstances/administrators/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/readme.md
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/readme.md
  arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
  arm/Microsoft.Sql/managedInstances/encryptionProtector/deploy.bicep
  arm/Microsoft.Sql/managedInstances/keys/deploy.bicep
  arm/Microsoft.Sql/managedInstances/securityAlertPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/deploy.bicep
  arm/Microsoft.Sql/servers/databases/deploy.bicep
  arm/Microsoft.Sql/servers/firewallRules/deploy.bicep
  arm/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
Labels: enhancement, [cat] modules

#602 Web Site child refactoring
  .github/workflows/ms.web.sites.yml
  arm/Microsoft.Web/serverfarms/.parameters/parameters.json
  arm/Microsoft.Web/serverfarms/deploy.bicep
  arm/Microsoft.Web/serverfarms/readme.md
  arm/Microsoft.Web/sites/.bicep/nested_components.bicep
  arm/Microsoft.Web/sites/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Web/sites/.bicep/nested_serverfarms.bicep
  arm/Microsoft.Web/sites/.parameters/fa.min.parameters.json
  arm/Microsoft.Web/sites/.parameters/fa.parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.min.parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.parameters.json
  arm/Microsoft.Web/sites/config/.bicep/nested_cuaId.bicep
  arm/Microsoft.Web/sites/config/deploy.bicep
  arm/Microsoft.Web/sites/config/readme.md
  arm/Microsoft.Web/sites/deploy.bicep
  arm/Microsoft.Web/sites/readme.md
Labels: [prio] medium, [cat] modules

#539 Added pattern to ModuleDesign wiki
  docs/wiki/ModulesDesign.md
  docs/wiki/TestingUsage.md
  docs/wiki/media/deploymentModel.png
  docs/wiki/media/templateOrchestration.png
  utilities/tools/Get-FormattedRBACRoles.ps1
Labels: documentation, enhancement

#616 Updated AutomationAccount with `existing`
  arm/Microsoft.Automation/automationAccounts/jobSchedules/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/modules/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/runbooks/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/schedules/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/softwareUpdateConfigurations/deploy.bicep
Labels: enhancement, [cat] modules

#626 Fixed incorrect token
  arm/Microsoft.Sql/servers/.parameters/parameters.json
Labels: bug, [cat] modules

#540 Added scope section to wiki & fixed relative links
  docs/wiki/Context.md
  docs/wiki/ContributionGuide.md
  docs/wiki/GettingStarted.md
  docs/wiki/Home.md
  docs/wiki/ModulesDesign.md
  docs/wiki/ParameterFileTokens.md
  docs/wiki/PipelinesDesign.md
  docs/wiki/PipelinesUsage.md
  docs/wiki/TestingDesign.md
  docs/wiki/TestingUsage.md
Labels: documentation

#630 Update ASE & connection input parameters to use `name`
  arm/Microsoft.Web/connections/.parameters/parameters.json
  arm/Microsoft.Web/connections/deploy.bicep
  arm/Microsoft.Web/connections/readme.md
  arm/Microsoft.Web/hostingEnvironments/.parameters/parameters.json
  arm/Microsoft.Web/hostingEnvironments/deploy.bicep
  arm/Microsoft.Web/hostingEnvironments/readme.md
  arm/Microsoft.Web/sites/config/readme.md
Labels: enhancement, [cat] modules

#631 Update AutoManage to use `name` input parameter
  arm/Microsoft.Automanage/accounts/.parameters/parameters.json
  arm/Microsoft.Automanage/accounts/deploy.bicep
  arm/Microsoft.Automanage/accounts/readme.md
Labels: enhancement, [cat] modules

#639 Removed temporal workaround from Module ReadMe Script
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  utilities/tools/Set-ModuleReadMe.ps1
Labels: documentation, [cat] modules

#641 Update the `Getting Started` section
  docs/wiki/GettingStarted.md
Labels: documentation

#647 (546) - Policy Set Definitions: Updated Module To Align with Other Resources
  .github/workflows/ms.authorization.policysetdefinitions.yml
  arm/Microsoft.Authorization/policySetDefinitions/.bicep/nested_policySetDefinition_mg.bicep
  arm/Microsoft.Authorization/policySetDefinitions/.bicep/nested_policySetDefinition_sub.bicep
  arm/Microsoft.Authorization/policySetDefinitions/.parameters/min.parameters.json
  arm/Microsoft.Authorization/policySetDefinitions/.parameters/parameters.json
  arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/readme.md
Labels: enhancement

#665 Updated the Set-ModuleReadMe script to dynamically populate the ParameterUsage section(s)
  utilities/tools/Set-ModuleReadMe.ps1
  utilities/tools/helper/Merge-FileWithNewContent.ps1
  utilities/tools/moduleReadMeSource/resourceUsage-privateEndpoints.md
  utilities/tools/moduleReadMeSource/resourceUsage-roleAssignments.md
  utilities/tools/moduleReadMeSource/resourceUsage-tags.md
Labels: bug, enhancement

#667 (546) - Policy Assignments: Updated Module To Align with Other Resources
  .github/workflows/ms.authorization.policyassignments.yml
  arm/Microsoft.Authorization/policyAssignments/.bicep/nested_policyAssignments_mg.bicep
  arm/Microsoft.Authorization/policyAssignments/.bicep/nested_policyAssignments_rg.bicep
  arm/Microsoft.Authorization/policyAssignments/.bicep/nested_policyAssignments_sub.bicep
  arm/Microsoft.Authorization/policyAssignments/.parameters/allowedLocations.parameters.json
  arm/Microsoft.Authorization/policyAssignments/.parameters/listOfAllowedSKUs.parameters.json
  arm/Microsoft.Authorization/policyAssignments/.parameters/min.parameters.json
  arm/Microsoft.Authorization/policyAssignments/.parameters/parameters.json
  arm/Microsoft.Authorization/policyAssignments/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/readme.md
Labels: enhancement

#642 (546) - RoleDefinitions: Updated Module To Align with Other Resources
  .github/workflows/ms.authorization.roledefinitions.yml
  arm/Microsoft.Authorization/roleDefinitions/.bicep/nested_roleDefinitions_mg.bicep
  arm/Microsoft.Authorization/roleDefinitions/.bicep/nested_roleDefinitions_rg.bicep
  arm/Microsoft.Authorization/roleDefinitions/.bicep/nested_roleDefinitions_sub.bicep
  arm/Microsoft.Authorization/roleDefinitions/.parameters/min.parameters.json
  arm/Microsoft.Authorization/roleDefinitions/.parameters/parameters.json
  arm/Microsoft.Authorization/roleDefinitions/deploy.bicep
  arm/Microsoft.Authorization/roleDefinitions/readme.md
Labels: enhancement

#681 Applied fix to main ReadMe script
  README.md
  arm/README.md
  utilities/tools/Set-GitHubReadMeModuleTable.ps1
Labels: documentation

#632 Update Storage to use `existing`
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/managementPolicies/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/tables/deploy.bicep
Labels: enhancement, [cat] modules

#689 Added dependency consideration for removal
  utilities/pipelines/resourceRemoval/Remove-DeployedModule.ps1
  utilities/pipelines/resourceRemoval/helper/Get-DependencyResourceNames.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-GeneralModule.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Resource.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-VirtualMachine.ps1
Labels: bug, [cat] modules

#664 Remove references to `removal tags` from the the wiki
  docs/wiki/KnownIssues.md
  docs/wiki/PipelinesDesign.md
Labels: documentation
