Repository Azure/ResourceModules, pull requests merged in 2021-12, with the labels that each got.

#699 Depedency pipeline cleanup
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Authorization/policyDefinitions/deploy.bicep
  utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
Labels: bug, [cat] testing

#701 Updated kind & added param file
  .github/workflows/ms.resources.deploymentscripts.yml
  arm/Microsoft.Resources/deploymentScripts/.parameters/cli.parameters.json
  arm/Microsoft.Resources/deploymentScripts/.parameters/ps.parameters.json
  arm/Microsoft.Resources/deploymentScripts/deploy.bicep
Labels: enhancement, [cat] modules

#706 Added RBAC to secret & key child modules
  arm/Microsoft.KeyVault/vaults/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
  arm/Microsoft.KeyVault/vaults/accessPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.KeyVault/vaults/accessPolicies/deploy.bicep
  arm/Microsoft.KeyVault/vaults/accessPolicies/readme.md
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/.bicep/nested_rbac.bicep
  arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.KeyVault/vaults/secrets/.bicep/nested_rbac.bicep
  arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
  arm/Microsoft.KeyVault/vaults/secrets/readme.md
Labels: enhancement, [cat] modules

#743 Fixed missing optional check in RSV
  .github/workflows/ms.recoveryservices.vaults.yml
  arm/Microsoft.RecoveryServices/vaults/.parameters/min.parameters.json
  arm/Microsoft.RecoveryServices/vaults/.parameters/parameters.json
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
Labels: bug, [cat] modules

#755 Added backup config to rsv module
  arm/Microsoft.RecoveryServices/vaults/.parameters/parameters.json
  arm/Microsoft.RecoveryServices/vaults/backupConfig/.bicep/nested_cuaId.bicep
  arm/Microsoft.RecoveryServices/vaults/backupConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupConfig/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/readme.md
Labels: enhancement, [cat] modules

#714 Role Assignments: Principal Type Update + Uplift API Version for Module
  arm/Microsoft.Authorization/roleAssignments/.bicep/nested_rbac_mg.bicep
  arm/Microsoft.Authorization/roleAssignments/.bicep/nested_rbac_rg.bicep
  arm/Microsoft.Authorization/roleAssignments/.bicep/nested_rbac_sub.bicep
  arm/Microsoft.Authorization/roleAssignments/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/readme.md
Labels: enhancement

#769 Modules Design update
  docs/wiki/ModulesDesign.md
Labels: documentation

#765 Add Missing Diagnostic Settings to Modules
  arm/Microsoft.OperationalInsights/workspaces/.parameters/parameters.json
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/readme.md
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/databases/deploy.bicep
  arm/Microsoft.Sql/servers/databases/readme.md
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/readme.md
  arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
  arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/readme.md
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/readme.md
  arm/Microsoft.Storage/storageAccounts/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/readme.md
Labels: enhancement, [cat] modules

#761 Users/simonb/517 automation account removal
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  utilities/pipelines/resourceRemoval/Remove-DeployedModule.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-AutomationAccount.ps1
Labels: [cat] testing

#748 Add Azure firewall policy module
  .github/workflows/ms.network.firewallpolicies.yml
  arm/Microsoft.Network/azureFirewalls/deploy.bicep
  arm/Microsoft.Network/azureFirewalls/readme.md
  arm/Microsoft.Network/firewallPolicies/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/firewallPolicies/.parameters/min.parameters.json
  arm/Microsoft.Network/firewallPolicies/.parameters/parameters.json
  arm/Microsoft.Network/firewallPolicies/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/readme.md
  arm/Microsoft.Network/firewallPolicies/ruleCollectionGroups/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/firewallPolicies/ruleCollectionGroups/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/ruleCollectionGroups/readme.md
  arm/Microsoft.Network/firewallPolicies/ruleGroups/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/firewallPolicies/ruleGroups/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/ruleGroups/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/readme.md
Labels: [cat] modules

#801 Updated deployed resource names in parameter files
  arm/Microsoft.AnalysisServices/servers/.parameters/min.parameters.json
  arm/Microsoft.ApiManagement/service/.parameters/max.parameters.json
  arm/Microsoft.Automation/automationAccounts/.parameters/min.parameters.json
  arm/Microsoft.Compute/galleries/.parameters/images.parameters.json
  arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
  arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
  arm/Microsoft.DesktopVirtualization/applicationgroups/.parameters/min.parameters.json
  arm/Microsoft.DocumentDB/databaseAccounts/.parameters/mongodb.parameters.json
  arm/Microsoft.DocumentDB/databaseAccounts/.parameters/plain.parameters.json
  arm/Microsoft.DocumentDB/databaseAccounts/.parameters/sqldb.parameters.json
  arm/Microsoft.NetApp/netAppAccounts/.parameters/min.parameters.json
  arm/Microsoft.NetApp/netAppAccounts/.parameters/nfs3.parameters.json
  arm/Microsoft.NetApp/netAppAccounts/.parameters/nfs41.parameters.json
  arm/Microsoft.Network/bastionHosts/.parameters/min.parameters.json
  arm/Microsoft.Network/firewallPolicies/.parameters/min.parameters.json
  arm/Microsoft.Network/privateEndpoints/.parameters/min.parameters.json
  arm/Microsoft.Network/privateEndpoints/.parameters/parameters.json
  arm/Microsoft.Network/virtualNetworkGateways/.parameters/expressRoute.parameters.json
  arm/Microsoft.Network/virtualNetworkGateways/.parameters/vpn.parameters.json
  arm/Microsoft.Network/virtualNetworks/.parameters/vnetPeering.parameters.json
  arm/Microsoft.OperationalInsights/workspaces/.parameters/min.parameters.json
  arm/Microsoft.RecoveryServices/vaults/.parameters/min.parameters.json
  arm/Microsoft.Resources/deploymentScripts/.parameters/cli.parameters.json
  arm/Microsoft.Resources/deploymentScripts/.parameters/ps.parameters.json
  arm/Microsoft.Web/sites/.parameters/fa.min.parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.min.parameters.json
  docs/wiki/ModulesDesign.md
Labels: documentation, [cat] modules

#746 Added Broken Link Check Action
  .github/workflows/platform.linkcheck.yml
  .lycheeignore
  arm/Microsoft.ApiManagement/service/portalsettings/readme.md
  arm/Microsoft.ApiManagement/service/readme.md
  arm/Microsoft.Automanage/accounts/readme.md
  arm/Microsoft.CognitiveServices/accounts/readme.md
  arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  arm/Microsoft.ContainerService/managedClusters/readme.md
  arm/Microsoft.EventGrid/topics/readme.md
  arm/Microsoft.HealthBot/healthBots/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
  arm/Microsoft.ManagedServices/registrationDefinitions/readme.md
  arm/Microsoft.Network/virtualNetworks/readme.md
  arm/Microsoft.ServiceBus/namespaces/queues/readme.md
  arm/Microsoft.ServiceBus/namespaces/readme.md
  arm/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
  arm/Microsoft.Sql/servers/securityAlertPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/readme.md
  arm/Microsoft.VirtualMachineImages/imageTemplates/readme.md
  arm/Microsoft.Web/sites/config/readme.md
  arm/Microsoft.Web/sites/readme.md
  docs/wiki/ContributionGuide.md
  docs/wiki/ModulesDesign.md
  docs/wiki/ModulesUsage.md
  docs/wiki/PipelinesDesign.md
  docs/wiki/TestingDesign.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: enhancement

#811 Update deployment code for Diagnostic Settings
  arm/Microsoft.AnalysisServices/servers/deploy.bicep
  arm/Microsoft.ApiManagement/service/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Batch/batchAccounts/deploy.bicep
  arm/Microsoft.CognitiveServices/accounts/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.DataFactory/factories/deploy.bicep
  arm/Microsoft.Databricks/workspaces/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
  arm/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
  arm/Microsoft.DesktopVirtualization/workspaces/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
  arm/Microsoft.EventGrid/topics/deploy.bicep
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.Logic/workflows/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
  arm/Microsoft.Network/azureFirewalls/deploy.bicep
  arm/Microsoft.Network/bastionHosts/.bicep/nested_publicIPAddress.bicep
  arm/Microsoft.Network/bastionHosts/deploy.bicep
  arm/Microsoft.Network/bastionHosts/readme.md
  arm/Microsoft.Network/expressRouteCircuits/deploy.bicep
  arm/Microsoft.Network/loadBalancers/deploy.bicep
  arm/Microsoft.Network/natGateways/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
  arm/Microsoft.Network/publicIPAddresses/deploy.bicep
  arm/Microsoft.Network/trafficmanagerprofiles/deploy.bicep
  arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Web/hostingEnvironments/deploy.bicep
  arm/Microsoft.Web/sites/deploy.bicep
Labels: enhancement, [cat] modules

#767 Extended removal logic to be more robust and in-depth
  .azuredevops/pipelineTemplates/module.jobs.deploy.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/workflows/ms.insights.diagnosticsettings.yml
  .github/workflows/ms.network.networkwatchers.yml
  docs/wiki/PipelinesDesign.md
  utilities/pipelines/resourceDeployment/New-ModuleDeployment.ps1
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
  utilities/pipelines/resourceRemoval/Remove-DeployedModule.ps1
  utilities/pipelines/resourceRemoval/helper/Get-DependencyResourceNameList.ps1
  utilities/pipelines/resourceRemoval/helper/Get-OrderedResourcesList.ps1
  utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsAsFormattedObjectList.ps1
  utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsOfDeployment.ps1
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourcePostRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-AutomationAccount.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-GeneralModule.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Resource.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-ResourceList.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-VirtualMachine.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-vWan.ps1
  utilities/pipelines/resourceValidation/Test-TemplateWithParameterFile.ps1
  utilities/pipelines/sharedScripts/Get-ScopeOfTemplateFile.ps1
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: enhancement, [cat] pipelines, [cat] testing

#814 Updated the use dependency filter to work with just a resourceId
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Labels: bug, [cat] pipelines

#817 Update action path in dependency pipeline
  .github/workflows/platform.dependencies.yml
Labels: [cat] pipelines, [cat] testing

#806 Expand Microsoft.ContainerService/managedClusters/agentPool properties object
  arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
  arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
  arm/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
Labels: enhancement, [cat] modules

#798 Update the global tests invocation to also consider child resources
  .azuredevops/pipelineTemplates/module.jobs.validate.yml
  .github/actions/templates/validateModulePester/action.yml
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Compute/virtualMachineScaleSets/extensions/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/extensions/readme.md
  arm/Microsoft.ContainerService/managedClusters/agentPools/.bicep/nested_cuaId.bicep
  arm/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  arm/Microsoft.DataFactory/factories/integrationRuntime/deploy.bicep
  arm/Microsoft.DataFactory/factories/integrationRuntime/readme.md
  arm/Microsoft.DataFactory/factories/managedVirtualNetwork/deploy.bicep
  arm/Microsoft.DataFactory/factories/managedVirtualNetwork/readme.md
  arm/Microsoft.Insights/privateLinkScopes/scopedResources/.bicep/nested_cuaId.bicep
  arm/Microsoft.Insights/privateLinkScopes/scopedResources/deploy.bicep
  arm/Microsoft.Insights/privateLinkScopes/scopedResources/readme.md
  arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
  arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/readme.md
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/readme.md
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/readme.md
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/readme.md
  arm/Microsoft.Sql/servers/firewallRules/deploy.bicep
  arm/Microsoft.Sql/servers/firewallRules/readme.md
  arm/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
  arm/Microsoft.Sql/servers/securityAlertPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/readme.md
  arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
Labels: bug, [cat] testing

#822 Users/lsnoddy/remove preview feature
  arm/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
Labels: [cat] modules

#824 Fixing PrivateDnsZone removal
  arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
  arm/Microsoft.Network/privateDnsZones/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/readme.md
  arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/readme.md
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsOfDeployment.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Labels: bug, enhancement, [cat] modules

#827 Updated ACR name + added min param file
  .azuredevops/modulePipelines/ms.containerregistry.registries.yml
  .github/workflows/ms.containerregistry.registries.yml
  arm/Microsoft.ContainerRegistry/registries/.parameters/min.parameters.json
  arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
Labels: [cat] modules

#831 Fixing disk encryption set module
  arm/Microsoft.Compute/diskEncryptionSets/.bicep/nested_kvAccessPolicy.bicep
  arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
  arm/Microsoft.Compute/diskEncryptionSets/readme.md
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: bug, [cat] modules, [cat] testing

#821 Adding tests and documentation for conversion script
  .github/workflows/platform.convertToArmTemplate.tests.yml
  docs/wiki/Home.md
  docs/wiki/Utilities.md
  docs/wiki/UtilitiesConversionScript.md
  docs/wiki/_Sidebar.md
  utilities/tools/ConvertTo-ARMTemplate.ps1
  utilities/tools/tests/ConvertTo-ARMTemplate.Tests.ps1
Labels: documentation, [cat] testing

#841 Fix Log analytics workspace removal
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/readme.md
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/deploy.bicep
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourcePostRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: bug, [cat] modules, [cat] testing

#840 Added further utilities readme files to Wiki
  README.md
  docs/wiki/Home.md
  docs/wiki/ModulesDesign.md
  docs/wiki/Utilities.md
  docs/wiki/UtilitiesConversionScript.md
  docs/wiki/UtilitiesConvertToARMTemplate.md
  docs/wiki/UtilitiesGetFormattedRBACRoleList.md
  docs/wiki/UtilitiesRegisterAzureDevOpsPipeline.md
  docs/wiki/UtilitiesSetModuleReadMe.md
  docs/wiki/media/rbacRoles.png
  utilities/tools/Get-FormattedRBACRoleList.ps1
  utilities/tools/Register-AzureDevOpsPipeline.ps1
  utilities/tools/Set-GitHubReadMeModuleTable.ps1
  utilities/tools/Set-ModuleReadMe.ps1
  utilities/tools/Test-ModuleLocally.ps1
Labels: documentation
