Repository Azure/ResourceModules, pull requests merged in 2021-10, with the labels that each got.

#313 Improve yaml parsing ++
  .github/actions/sharedScripts/Set-EnvironmentOnAgent.ps1
  .github/actions/templates/getWorkflowInput/scripts/Get-WorkflowDefaultInput.ps1
  .github/actions/templates/validateModuleApis/action.yml
  .github/actions/templates/validateModuleGeneral/action.yml
  arm/.global/global.module.tests.ps1
Labels: bug, enhancement

#314 Fixed a bug to improve Linux compatibility
  .github/workflows/scripts/helper/Get-ModulesAsMarkdownTable.ps1
  arm/.global/global.module.tests.ps1
  docs/wiki/Pipelines.md
  utilities/tools/ConvertTo-ARMTemplate.ps1
Labels: bug

#306 Bug Fixes - Automanage & Registrations Definitions
  .github/workflows/ms.apimanagement.service.apis.yml
  .github/workflows/ms.apimanagement.service.authorizationservers.yml
  .github/workflows/ms.apimanagement.service.backends.yml
  .github/workflows/ms.apimanagement.service.caches.yml
  .github/workflows/ms.apimanagement.service.namedvalues.yml
  .github/workflows/ms.apimanagement.service.products.yml
  .github/workflows/ms.apimanagement.service.subscriptions.yml
  .github/workflows/ms.apimanagement.service.yml
  .github/workflows/ms.authorization.policyassignments.yml
  .github/workflows/ms.authorization.policydefinitions.yml
  .github/workflows/ms.authorization.policyexemptions.yml
  .github/workflows/ms.authorization.policysetdefinitions.yml
  .github/workflows/ms.authorization.roleassignments.yml
  .github/workflows/ms.authorization.roledefinitions.yml
  .github/workflows/ms.automation.automationaccounts.softwareupdateconfigurations.yml
  .github/workflows/ms.cognitiveservices.accounts.yml
  .github/workflows/ms.consumption.budgets.yml
  .github/workflows/ms.eventhub.namespaces.eventhubs.yml
  .github/workflows/ms.insights.diagnosticsettings.yml
  .github/workflows/ms.keyvault.vaults.yml
  .github/workflows/ms.managedservices.registrationdefinitions.yml
  .github/workflows/ms.management.managementgroups.yml
  .github/workflows/ms.network.networkwatchers.yml
  .github/workflows/ms.network.virtualnetworks.virtualnetworkpeerings.yml
  .github/workflows/ms.security.azuresecuritycenter.yml
  .github/workflows/ms.servicebus.namespaces.queues.yml
  arm/Microsoft.Automanage/accounts/.parameters/parameters.json
  arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
  arm/Microsoft.ServiceBus/namespacesResources/queues/readme.md
Labels: bug

#315 Restored Service Bus Namespace RBAC, Changed instance name for Namespace and Queues.
  arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
  arm/Microsoft.ServiceBus/namespaces/.parameters/parameters.json
  arm/Microsoft.ServiceBus/namespacesResources/queues/.parameters/parameters.json
Labels: enhancement

#316 Fixed markdown gen
  .github/workflows/scripts/helper/Get-ModulesAsMarkdownTable.ps1
  README.md
  arm/README.md
Labels: bug
