Repository Azure/ResourceModules, pull requests merged in 2022-04, with the labels that each got.

#1204 Databricks BugFix: Added condition to diagnosticSettings
  arm/Microsoft.Databricks/workspaces/deploy.bicep
Labels: bug

#1208 Links Check - Add new exclusion + FW Policy - Parameter Usage URL Fix
  .lycheeignore
  arm/Microsoft.Network/firewallPolicies/ruleGroups/readme.md
Labels: bug

#1215 Cognitive Services: Added additional parameters
  arm/Microsoft.CognitiveServices/accounts/deploy.bicep
  arm/Microsoft.CognitiveServices/accounts/readme.md
Labels: enhancement, [cat] modules

#1217 Removed 'RuleGroups' Child Module from Firewall Policies
  arm/Microsoft.Network/firewallPolicies/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/readme.md
  arm/Microsoft.Network/firewallPolicies/ruleGroups/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/ruleGroups/readme.md
  arm/Microsoft.Network/firewallPolicies/ruleGroups/version.json
Labels: bug

#1213 SQLServer: Fix for extended parameter set
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/databases/deploy.bicep
  arm/Microsoft.Sql/servers/databases/readme.md
  arm/Microsoft.Sql/servers/deploy.bicep
Labels: bug, [cat] modules

#1223 Wiki restructuring - The context
  docs/wiki/Home.md
  docs/wiki/Solution creation.md
  docs/wiki/The context - CARML CI environment.md
  docs/wiki/The context - CARML library.md
  docs/wiki/The context - CARML overview.md
  docs/wiki/The context - IaC.md
  docs/wiki/The context.md
  docs/wiki/media/Context/CARLM_overview.png
  docs/wiki/media/Context/Deployment_flow.png
  docs/wiki/media/Context/Deployment_flow_detail_white.png
  docs/wiki/media/Context/Deployment_flow_users.png
  docs/wiki/media/Context/Library_storage-variants.png
Labels: documentation

#999 Users/sogangul/bicep add multi repo solution - Publish Wiki Guidelines for Multi-repo Orchestration with CARML
  docs/media/MultiRepoTestFolderStructure.png
  docs/wiki/Solution creation.md
Labels: documentation

#1228 AKS: Updated api version
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
Labels: bug, [cat] modules

#1238 Added support for multi-line metadata
  arm/Microsoft.Compute/availabilitySets/deploy.bicep
  arm/Microsoft.Compute/availabilitySets/readme.md
  arm/Microsoft.Insights/components/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.KubernetesConfiguration/extensions/readme.md
  arm/Microsoft.KubernetesConfiguration/fluxConfigurations/readme.md
  arm/Microsoft.Network/firewallPolicies/deploy.bicep
  utilities/tools/Set-ModuleReadMe.ps1
Labels: enhancement, [cat] modules

#1188 Cse fix
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
Labels: bug, [cat] modules

#1257 Fixed GitHub parameter fetch
  .github/actions/templates/getParameterFiles/action.yml
Labels: bug, [prio] high, [cat] pipelines, [cat] github

#1229 Wiki restructuring - CI environment
  docs/wiki/Getting started - Dependency pipeline.md
  docs/wiki/Getting started - Setup environment.md
  docs/wiki/Home.md
  docs/wiki/The CI environment - Deployment validation.md
  docs/wiki/The CI environment - Pipeline design.md
  docs/wiki/The CI environment - Pipeline usage.md
  docs/wiki/The CI environment - Publishing.md
  docs/wiki/The CI environment - Static validation.md
  docs/wiki/The CI environment.md
  docs/wiki/Upgrade from 0.3.1 to 0.4.0.md
  docs/wiki/media/CIEnvironment/dependencyPipelineInput.PNG
  docs/wiki/media/CIEnvironment/deploymentValidationOutput.png
  docs/wiki/media/CIEnvironment/deploymentValidationStep.png
  docs/wiki/media/CIEnvironment/modulePipelineInput.PNG
  docs/wiki/media/CIEnvironment/pipelineDesign.png
  docs/wiki/media/CIEnvironment/pipelineDesignPhases.png
  docs/wiki/media/CIEnvironment/pipelinePhasesADO.png
  docs/wiki/media/CIEnvironment/pipelinePhasesGH.png
  docs/wiki/media/CIEnvironment/publishingOutput.png
  docs/wiki/media/CIEnvironment/publishingStep.png
  docs/wiki/media/CIEnvironment/staticValidationOutput.png
  docs/wiki/media/CIEnvironment/staticValidationStep.png
Labels: documentation

#1286 Main home readme update
  README.md
  arm/Microsoft.AnalysisServices/servers/readme.md
  arm/Microsoft.DesktopVirtualization/scalingplans/readme.md
  arm/Microsoft.EventGrid/systemTopics/readme.md
  arm/Microsoft.KubernetesConfiguration/extensions/readme.md
  arm/Microsoft.KubernetesConfiguration/fluxConfigurations/readme.md
  arm/Microsoft.Network/firewallPolicies/readme.md
  arm/Microsoft.Network/frontDoors/readme.md
  arm/Microsoft.Network/virtualHubs/readme.md
  arm/Microsoft.Network/vpnSites/readme.md
  arm/Microsoft.ServiceFabric/clusters/applicationTypes/readme.md
  arm/Microsoft.ServiceFabric/clusters/readme.md
  arm/Microsoft.Synapse/privateLinkHubs/readme.md
  arm/Microsoft.Web/staticSites/readme.md
  arm/README.md
Labels: documentation

#1285 Fix deployment validation at scope different than rg
  .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
  .github/actions/templates/validateModuleDeployment/action.yml
Labels: bug, [cat] pipelines, [cat] github, [cat] azure devops

#1269 Introduce YAML templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, [cat] github

#1289 Wiki restructuring - Getting started update
  docs/wiki/Contribution guide - Contribution flow.md
  docs/wiki/Getting started - Check NamePrefix availability.md
  docs/wiki/Getting started - Scenario 1 Onboard module library and CI environment.md
  docs/wiki/Getting started - Scenario 2 Consume library.md
  docs/wiki/Getting started - Scenario 3 Contribute.md
  docs/wiki/Getting started.md
  docs/wiki/Home.md
  docs/wiki/Solution creation.md
  docs/wiki/The CI environment - Token replacement.md
  docs/wiki/The library - Module design.md
Labels: documentation, enhancement

#1290 [VNET] Fixed incorrect resource name
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
Labels: bug, [cat] modules

#1283 Added `bicepconfig.json` to disable location warning
  bicepconfig.json
  docs/wiki/The CI environment - Bicep configuration file.md
  docs/wiki/The CI environment.md
Labels: enhancement

#1262 [VNET] Remove `batch` for subnets
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
Labels: bug, [cat] modules

#1266 [Netapp] Removed `batch` for Capacity Pools
  arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
Labels: bug, [cat] modules

#1264 [OperationalInsights] Removed `batch` for solutions deployment
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
Labels: bug, [cat] modules

#1293 Added Cosmos DB and Containers support for Defender for Cloud Settings
  arm/Microsoft.Security/azureSecurityCenter/deploy.bicep
  arm/Microsoft.Security/azureSecurityCenter/readme.md
  arm/Microsoft.Security/azureSecurityCenter/version.json
Labels: enhancement, [cat] modules

#1263 [FirewallPolicies] Removed `batch` for ruleCollectionGroups
  arm/Microsoft.Network/firewallPolicies/deploy.bicep
Labels: bug, [cat] modules

#1267 [Pester] Added test to make sure the `Set-ModuleReadMe` script was applied
  arm/.global/global.module.tests.ps1
  utilities/tools/Set-ModuleReadMe.ps1
Labels: [cat] modules, [cat] testing

#1296 Fix dependency pipeline
  .github/workflows/platform.dependencies.yml
Labels: bug, enhancement, [cat] testing

#1303 Wiki restructuring - images
  docs/wiki/Context.md
  docs/wiki/Contribution guide - Get formatted RBAC roles.md
  docs/wiki/Solution creation.md
  docs/wiki/TestingDesign.md
  docs/wiki/The CI environment - Deployment validation.md
  docs/wiki/The CI environment - Pipeline design.md
  docs/wiki/The CI environment - Publishing.md
  docs/wiki/The CI environment - Static validation.md
  docs/wiki/The context - CARML CI environment.md
  docs/wiki/The context - CARML library.md
  docs/wiki/The context - CARML overview.md
  docs/wiki/UtilitiesGetFormattedRBACRoleList.md
Labels: bug, documentation, enhancement

#1194 Addition of new Module - Azure Active Directory Domain Services(Azure ADDS)
  .azuredevops/modulePipelines/ms.aad.domainservices.yml
  .github/workflows/ms.aad.domainservices.yml
  arm/Microsoft.AAD/DomainServices/.bicep/nested_rbac.bicep
  arm/Microsoft.AAD/DomainServices/.parameters/parameters.json
  arm/Microsoft.AAD/DomainServices/deploy.bicep
  arm/Microsoft.AAD/DomainServices/readme.md
  arm/Microsoft.AAD/DomainServices/version.json
Labels: [cat] modules

#1230 Wiki restructuring - switch updated content
  docs/wiki/Context.md
  docs/wiki/ContributionGuide.md
  docs/wiki/GettingStarted.md
  docs/wiki/Home.md
  docs/wiki/KnownIssues.md
  docs/wiki/Modules.md
  docs/wiki/ModulesDesign.md
  docs/wiki/ModulesUsage.md
  docs/wiki/ParameterFileTokens.md
  docs/wiki/PipelineRemovalAction.md
  docs/wiki/Pipelines.md
  docs/wiki/PipelinesDesign.md
  docs/wiki/PipelinesUsage.md
  docs/wiki/Testing.md
  docs/wiki/TestingDesign.md
  docs/wiki/TestingUsage.md
  docs/wiki/The CI environment - GitHub ReadMe module table update.md
  docs/wiki/The CI environment - Pipeline design.md
  docs/wiki/The CI environment.md
  docs/wiki/Utilities.md
  docs/wiki/UtilitiesConvertToARMTemplate.md
  docs/wiki/UtilitiesGetFormattedRBACRoleList.md
  docs/wiki/UtilitiesRegisterAzureDevOpsPipeline.md
  docs/wiki/UtilitiesSetModuleReadMe.md
  docs/wiki/UtilitiesTestModuleLocally.md
  docs/wiki/_Sidebar.md
Labels: documentation

#1305 all readmes regenerated
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.Web/serverfarms/readme.md
Labels: bug, documentation, enhancement, [cat] testing

#1259 Adjusted test for tokens in parameter files
  .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
  .github/actions/templates/validateModulePester/action.yml
  arm/.global/global.module.tests.ps1
  docs/wiki/The CI environment - Static validation.md
  utilities/tools/Test-ModuleLocally.ps1
Labels: [prio] high, [cat] pipelines, [cat] modules, [cat] testing

#1312 Fix Home readme status badges
  README.md
  utilities/tools/helper/Get-ModulesAsMarkdownTable.ps1
Labels: bug, documentation, [cat] pipelines

#1313 [VM] Updated SKU
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.min.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.min.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
Labels: bug, [cat] modules

#1316 Updating general removal sequence (fixing PE removal)
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
Labels: bug, enhancement, [cat] pipelines, [cat] testing

#1314 Fix home tooling section
  README.md
Labels: bug, documentation, enhancement

#1317 [Pester] Fixed an issue with the runtime optimization
  arm/.global/global.module.tests.ps1
Labels: bug, [cat] modules, [cat] testing

#1304 [AADDS] Follow Up PR
  .azuredevops/modulePipelines/ms.aad.domainservices.yml
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/ms.aad.domainservices.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.AAD/DomainServices/.parameters/parameters.json
  arm/Microsoft.AAD/DomainServices/deploy.bicep
  arm/Microsoft.AAD/DomainServices/readme.md
  arm/Microsoft.Network/virtualNetworks/.parameters/parameters.json
  docs/wiki/Known issues.md
  utilities/pipelines/dependencies/Microsoft.Network/networkSecurityGroups/parameters/aadds.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/8.aadds.parameters.json
Labels: bug, [cat] modules

#1324 Added telemetry flag
  arm/Microsoft.ApiManagement/service/apis/deploy.bicep
  arm/Microsoft.ApiManagement/service/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/deploy.bicep
  arm/Microsoft.Authorization/policyDefinitions/deploy.bicep
  arm/Microsoft.Authorization/policyExemptions/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/deploy.bicep
  arm/Microsoft.Authorization/roleDefinitions/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Compute/galleries/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.DataFactory/factories/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/deploy.bicep
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
  arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.NetApp/netAppAccounts/capacityPools/deploy.bicep
  arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/deploy.bicep
  arm/Microsoft.Network/loadBalancers/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
  arm/Microsoft.Network/networkWatchers/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/deploy.bicep
  arm/Microsoft.Network/privateEndpoints/deploy.bicep
  arm/Microsoft.Network/virtualHubs/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.Network/vpnGateways/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/replicationFabrics/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/deploy.bicep
  arm/Microsoft.Resources/tags/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/queues/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/topics/deploy.bicep
  arm/Microsoft.ServiceFabric/clusters/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
  arm/Microsoft.Web/sites/deploy.bicep
  constructs/Microsoft.Authorization/roleAssignments-multiRolesMultiPrincipals/readme.md
  constructs/Microsoft.Network/virtualNetwork/virtualNetworkPeerings-multiRemoteVnets/readme.md
Labels: bug, [cat] modules

#1308 Document prereq for ADO Universal Artifact Feed
  docs/wiki/Getting started - Scenario 1 Onboard module library and CI environment.md
Labels: documentation

#1321 add subnet rbac
  arm/Microsoft.Network/virtualNetworks/.parameters/parameters.json
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/subnets/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/virtualNetworks/subnets/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/subnets/readme.md
Labels: enhancement, [cat] modules

#1298 Users/jozessi/updateaml
  arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
  arm/Microsoft.MachineLearningServices/workspaces/computes/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/computes/readme.md
  arm/Microsoft.MachineLearningServices/workspaces/computes/version.json
  arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
Labels: [cat] modules

#1258 Updating sites module
  arm/Microsoft.Web/sites/.bicep/nested_components.bicep
  arm/Microsoft.Web/sites/.bicep/nested_serverfarms.bicep
  arm/Microsoft.Web/sites/.parameters/fa.parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.parameters.json
  arm/Microsoft.Web/sites/config-appsettings/deploy.bicep
  arm/Microsoft.Web/sites/config-appsettings/readme.md
  arm/Microsoft.Web/sites/config-appsettings/version.json
  arm/Microsoft.Web/sites/config-authsettingsv2/deploy.bicep
  arm/Microsoft.Web/sites/config-authsettingsv2/readme.md
  arm/Microsoft.Web/sites/config-authsettingsv2/version.json
  arm/Microsoft.Web/sites/config/deploy.bicep
  arm/Microsoft.Web/sites/config/readme.md
  arm/Microsoft.Web/sites/deploy.bicep
  arm/Microsoft.Web/sites/readme.md
  docs/wiki/Getting started - Scenario 1 Onboard module library and CI environment.md
Labels: enhancement, [cat] modules

#1294 changed virtualnetworkrules to use resourceid instead of name
  arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.EventHub/namespaces/readme.md
  arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/readme.md
Labels: enhancement, [cat] modules

#1330 Added function app to prevent serverfarm auto-removal
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  utilities/pipelines/dependencies/Microsoft.Web/sites/parameters/parameters.json
Labels: enhancement, [cat] testing

#1326 Fixed local tests ref
  .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
  .github/actions/templates/validateModulePester/action.yml
  utilities/tools/Test-ModuleLocally.ps1
Labels: bug, [cat] pipelines, [cat] testing

#1331 Updated the update of the login context to plain subscription ID
  utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
Labels: bug, [cat] pipelines

#1336 Storage: Added IP test
  arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
  arm/Microsoft.Storage/storageAccounts/readme.md
Labels: enhancement, [cat] testing

#1327 Users/msanzdelrio/vngw ip fix
  arm/Microsoft.Network/virtualNetworkGateways/.parameters/expressRoute.parameters.json
  arm/Microsoft.Network/virtualNetworkGateways/.parameters/vpn.parameters.json
  arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
  arm/Microsoft.Network/virtualNetworkGateways/readme.md
Labels: bug, [cat] modules

#1335 Updated login in Test-Script to align with Deploy-Script
  utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
Labels: bug, [cat] pipelines

#1338 Users/alsehr/fix contr link
  README.md
Labels: documentation

#1339 Align ADO removeDeployment default input parameter
  .azuredevops/modulePipelines/ms.apimanagement.service.yml
  .azuredevops/modulePipelines/ms.cognitiveservices.accounts.yml
  .azuredevops/modulePipelines/ms.insights.diagnosticsettings.yml
  .azuredevops/modulePipelines/ms.keyvault.vaults.yml
  .azuredevops/modulePipelines/ms.kubernetesconfiguration.extensions.yml
  .azuredevops/modulePipelines/ms.kubernetesconfiguration.fluxconfigurations.yml
  .azuredevops/modulePipelines/ms.network.networkwatchers.yml
Labels: bug, [cat] pipelines, [cat] azure devops
