Repository Azure/ResourceModules, pull requests merged in 2022-03, with the labels that each got.

#1059 Add dedicated LAW for automation account test
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.Insights/components/.parameters/parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.parameters.json
  docs/wiki/TestingDesign.md
  utilities/pipelines/dependencies/Microsoft.Insights/components/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.OperationalInsights/workspaces/parameters/appi.parameters.json
  utilities/pipelines/dependencies/Microsoft.OperationalInsights/workspaces/parameters/aut.parameters.json
Labels: [cat] modules, [cat] testing

#1064 Wiki restructuring - known issues
  docs/wiki/Home.md
  docs/wiki/Known issues.md
Labels: documentation

#1065 KeyVault: Updated roles
  arm/Microsoft.KeyVault/vaults/.bicep/nested_rbac.bicep
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
  arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
Labels: [cat] modules

#1068 VPN Gateway: Added module
  .azuredevops/modulePipelines/ms.network.vpnGateways.yml
  .github/workflows/ms.network.vpngateways.yml
  arm/Microsoft.Network/vpnGateways/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/vpnGateways/.parameters/min.parameters.json
  arm/Microsoft.Network/vpnGateways/.parameters/parameters.json
  arm/Microsoft.Network/vpnGateways/connections/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/vpnGateways/connections/deploy.bicep
  arm/Microsoft.Network/vpnGateways/connections/readme.md
  arm/Microsoft.Network/vpnGateways/connections/version.json
  arm/Microsoft.Network/vpnGateways/deploy.bicep
  arm/Microsoft.Network/vpnGateways/natRules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/vpnGateways/natRules/deploy.bicep
  arm/Microsoft.Network/vpnGateways/natRules/readme.md
  arm/Microsoft.Network/vpnGateways/natRules/version.json
  arm/Microsoft.Network/vpnGateways/readme.md
  arm/Microsoft.Network/vpnGateways/version.json
Labels: enhancement, [cat] modules

#1074 Wiki restructuring - interoperability
  docs/wiki/Home.md
  docs/wiki/Interoperability - Bicep to ARM conversion.md
  docs/wiki/Interoperability - Register ADO pipelines.md
  docs/wiki/Interoperability - Register Azure DevOps Pipelines.md
  docs/wiki/Interoperability.md
Labels: documentation

#1080 Fix typo for new module workflows
  .azuredevops/modulePipelines/ms.network.virtualhubs.yml
  .azuredevops/modulePipelines/ms.network.vpngateways.yml
  .github/workflows/ms.network.virtualhubs.yml
  .github/workflows/ms.network.vpngateways.yml
Labels: [cat] pipelines

#1081 VNET: Removed subnet property from main deployment
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
Labels: bug, [cat] modules

#1084 Wiki restructuring - Contribution guide
  docs/wiki/Contribution guide - Contribution flow.md
  docs/wiki/Contribution guide - Generate module readme.md
  docs/wiki/Contribution guide - Get formatted RBAC roles.md
  docs/wiki/Contribution guide.md
  docs/wiki/Home.md
  docs/wiki/media/badgeDropdown.png
  docs/wiki/media/carmlStatusBadge.png
Labels: documentation

#1087 Wiki restructure - The library
  docs/wiki/The library - Module design.md
  docs/wiki/The library - Module usage.md
  docs/wiki/The library.md
Labels: documentation

#1088 VPN Site: Created new module
  .azuredevops/modulePipelines/ms.network.vpnsites.yml
  .github/workflows/ms.network.vpnsites.yml
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Network/virtualHubs/deploy.bicep
  arm/Microsoft.Network/vpnSites/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/vpnSites/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/vpnSites/.parameters/min.parameters.json
  arm/Microsoft.Network/vpnSites/.parameters/parameters.json
  arm/Microsoft.Network/vpnSites/deploy.bicep
  arm/Microsoft.Network/vpnSites/readme.md
  arm/Microsoft.Network/vpnSites/version.json
Labels: [cat] modules, [cat] testing

#1090 vWAN: Moved resources to corresponding modules and removed duplicates
  .azuredevops/modulePipelines/ms.network.virtualwans.yml
  .github/workflows/ms.network.virtualwans.yml
  arm/Microsoft.Network/virtualHubs/deploy.bicep
  arm/Microsoft.Network/virtualHubs/readme.md
  arm/Microsoft.Network/virtualWans/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/virtualWans/.parameters/min.parameters.json
  arm/Microsoft.Network/virtualWans/.parameters/parameters.json
  arm/Microsoft.Network/virtualWans/deploy.bicep
  arm/Microsoft.Network/virtualWans/readme.md
  arm/Microsoft.Network/vpnGateways/deploy.bicep
  arm/Microsoft.Network/vpnGateways/readme.md
Labels: [cat] modules

#1079 Adding properties to Azure Container Registry
  arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/readme.md
  arm/Microsoft.ContainerRegistry/registries/replications/.bicep/nested_cuaId.bicep
  arm/Microsoft.ContainerRegistry/registries/replications/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/replications/readme.md
  arm/Microsoft.ContainerRegistry/registries/replications/version.json
Labels: enhancement, [cat] modules

#1110 Bug fix: Update ADO Dependency Pipeline to support new policy assignment parameter file names, point to the root template instead of child
  .azuredevops/platformPipelines/platform.dependencies.yml
Labels: bug, [cat] pipelines

#1106 add Azure Active Directory as sql server admin authentication
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/readme.md
Labels: enhancement, [cat] modules

#1118 Added private endpoint deployment to container registry
  arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
Labels: [cat] modules, [cat] testing

#1102 NSG: Moved NSG Security Rules into its own child-module
  .azuredevops/modulePipelines/ms.network.networksecuritygroups.yml
  .github/workflows/ms.network.networksecuritygroups.yml
  arm/Microsoft.Network/networkSecurityGroups/.parameters/min.parameters.json
  arm/Microsoft.Network/networkSecurityGroups/.parameters/parameters.json
  arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/readme.md
  arm/Microsoft.Network/networkSecurityGroups/securityRules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/networkSecurityGroups/securityRules/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/securityRules/readme.md
  arm/Microsoft.Network/networkSecurityGroups/securityRules/version.json
Labels: [cat] modules

#1116 Added additional test case for SQL Server
  .azuredevops/modulePipelines/ms.sql.servers.yml
  .github/workflows/ms.sql.servers.yml
  arm/Microsoft.Sql/servers/.parameters/admin.parameters.json
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/readme.md
Labels: [cat] modules, [cat] testing

#1112 Virtual Network - Subnet Child Resource Remediation
  arm/Microsoft.Authorization/policyAssignments/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/.parameters/parameters.json
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/subnets/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/subnets/readme.md
  utilities/pipelines/dependencies/Microsoft.Network/networkSecurityGroups/parameters/apgw.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/networkSecurityGroups/parameters/ase.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/networkSecurityGroups/parameters/bastion.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/1.bastion.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/2.vnetpeer01.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/3.vnetpeer02.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/4.azfw.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/5.aks.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/6.sqlmi.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/7.virtualHubConnection.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/parameters.json
Labels: bug, [prio] high, [cat] modules

#1125 Added script to check prefix
  docs/wiki/Getting started - Check NamePrefix availability.md
  docs/wiki/Getting started - Setup environment.md
  utilities/tools/Test-ModuleLocally.ps1
  utilities/tools/Test-NamePrefixAvailability.ps1
Labels: enhancement

#1129 Aligned lock API versions across modules
  arm/Microsoft.ServiceFabric/clusters/deploy.bicep
  arm/Microsoft.ServiceFabric/clusters/readme.md
Labels: [cat] modules

#1143 Added proximity placement groups in the ADO dependency pipeline
  .azuredevops/platformPipelines/platform.dependencies.yml
Labels: bug, [cat] pipelines

#1166 VNET: Added example for VNET subnet parameter
  arm/Microsoft.Network/virtualNetworks/readme.md
Labels: documentation, [cat] modules

#1162 Updated deployment examples for modules/templates
  docs/wiki/The library - Module usage.md
Labels: documentation, enhancement

#1161 Module frontdoor
  .azuredevops/modulePipelines/ms.network.frontdoors.yml
  .github/workflows/ms.network.frontdoors.yml
  arm/Microsoft.Network/frontDoors/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/frontDoors/.parameters/parameters.json
  arm/Microsoft.Network/frontDoors/deploy.bicep
  arm/Microsoft.Network/frontDoors/readme.md
  arm/Microsoft.Network/frontDoors/version.json
Labels: enhancement, [cat] modules

#1164 Users/alsehr/1158 web parent
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Web/sites/.parameters/fa.min.parameters.json
  arm/Microsoft.Web/sites/.parameters/fa.parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.min.parameters.json
  arm/Microsoft.Web/sites/.parameters/wa.parameters.json
  arm/Microsoft.Web/sites/deploy.bicep
  arm/Microsoft.Web/sites/readme.md
  utilities/pipelines/dependencies/Microsoft.Web/serverfarms/parameters/parameters.json
Labels: [cat] modules

#1168 Updated endpoint docs
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.CognitiveServices/accounts/readme.md
  arm/Microsoft.Compute/disks/readme.md
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.ContainerRegistry/registries/readme.md
  arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  arm/Microsoft.EventGrid/systemTopics/readme.md
  arm/Microsoft.EventGrid/topics/readme.md
  arm/Microsoft.EventHub/namespaces/readme.md
  arm/Microsoft.Insights/privateLinkScopes/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
  arm/Microsoft.Network/applicationGateways/readme.md
  arm/Microsoft.Network/localNetworkGateways/readme.md
  arm/Microsoft.Network/natGateways/readme.md
  arm/Microsoft.Network/networkSecurityGroups/readme.md
  arm/Microsoft.Network/vpnSites/readme.md
  arm/Microsoft.RecoveryServices/vaults/readme.md
  arm/Microsoft.ServiceBus/namespaces/readme.md
  arm/Microsoft.ServiceBus/namespaces/topics/authorizationRules/readme.md
  arm/Microsoft.ServiceFabric/clusters/readme.md
  arm/Microsoft.Sql/managedInstances/readme.md
  arm/Microsoft.Storage/storageAccounts/readme.md
  arm/Microsoft.Synapse/privateLinkHubs/readme.md
  arm/Microsoft.Web/sites/readme.md
  arm/Microsoft.Web/staticSites/readme.md
  constructs/Microsoft.Authorization/roleAssignments-multiRolesMultiPrincipals/readme.md
  utilities/tools/moduleReadMeSource/resourceUsage-privateEndpoints.md
Labels: documentation, [cat] modules

#1128 Added documentation to current composite actions
  .github/actions/templates/getWorkflowInput/action.yml
  .github/actions/templates/publishModule/action.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/actions/templates/validateModulePester/action.yml
Labels: documentation

#1049 Set default values to a secure value - Automation #773
  .azuredevops/modulePipelines/ms.automation.automationaccounts.yml
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/ms.automation.automationaccounts.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Automation/automationAccounts/.parameters/encr.parameters.json
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.Automation/automationAccounts/variables/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/variables/readme.md
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/nopr.parameters.json
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/fa.parameters.json
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/law.parameters.json
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/parameters.json
Labels: enhancement, [cat] modules

#1170 Update Readme generator to allow parameter table categories (Storage Account)
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/readme.md
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
  arm/Microsoft.Storage/storageAccounts/managementPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/readme.md
  arm/Microsoft.Storage/storageAccounts/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/tables/readme.md
  docs/wiki/The library - Module design.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: documentation, enhancement

#1176 Extended ReadMe generator
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/readme.md
  arm/Microsoft.Storage/storageAccounts/blobServices/readme.md
  arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
  arm/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
  arm/Microsoft.Storage/storageAccounts/managementPolicies/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/queues/readme.md
  arm/Microsoft.Storage/storageAccounts/queueServices/readme.md
  arm/Microsoft.Storage/storageAccounts/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/readme.md
  arm/Microsoft.Storage/storageAccounts/tableServices/tables/readme.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: documentation, [cat] modules

#1183 Follow up fix for RBAC update
  arm/Microsoft.Resources/resourceGroups/.bicep/nested_rbac.bicep
  arm/Microsoft.Resources/resourceGroups/deploy.bicep
Labels: bug, [cat] modules

#1199 VNET: Updated peering dependency
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
Labels: bug, [cat] modules
