Repository Azure/ResourceModules, pull requests merged in 2022-01, with the labels that each got.

#851 Added missing ADO artifacts reference in wiki
  docs/wiki/PipelinesDesign.md
Labels: documentation, [cat] azure devops

#850 Added deleteOption to VM
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.min.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.min.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
  docs/wiki/KnownIssues.md
Labels: enhancement, [cat] modules, [cat] testing

#848 LoadBalancer: Added child resources + test cases
  .azuredevops/modulePipelines/ms.network.loadbalancers.yml
  .github/workflows/ms.network.loadbalancers.yml
  arm/Microsoft.Network/loadBalancers/.parameters/min.parameters.json
  arm/Microsoft.Network/loadBalancers/.parameters/parameters.json
  arm/Microsoft.Network/loadBalancers/backendAddressPools/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/loadBalancers/backendAddressPools/deploy.bicep
  arm/Microsoft.Network/loadBalancers/backendAddressPools/readme.md
  arm/Microsoft.Network/loadBalancers/deploy.bicep
  arm/Microsoft.Network/loadBalancers/inboundNatRules/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/loadBalancers/inboundNatRules/deploy.bicep
  arm/Microsoft.Network/loadBalancers/inboundNatRules/readme.md
  arm/Microsoft.Network/loadBalancers/readme.md
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Labels: enhancement, [cat] modules, [cat] testing

#845 VNET: Fixed indempotency bug with subnet deployment
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
Labels: bug, [cat] modules

#854 Added missing removal condition to avoid uncancelable pipeline
  .azuredevops/pipelineTemplates/module.jobs.deploy.yml
Labels: bug, [cat] pipelines, [cat] azure devops

#862 Fix Recovery Services Vault MI Issue
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
Labels: bug, [cat] modules

#863 Update global.variables.yml
  .azuredevops/pipelineVariables/global.variables.yml
Labels: documentation, enhancement

#847 Added utilities wiki entry
  docs/wiki/Home.md
  docs/wiki/UtilitiesConvertToARMTemplate.md
  docs/wiki/UtilitiesGetFormattedRBACRoleList.md
  docs/wiki/UtilitiesRegisterAzureDevOpsPipeline.md
  docs/wiki/UtilitiesSetGitHubReadMeModuleTable.md
  docs/wiki/UtilitiesSetModuleReadMe.md
  docs/wiki/UtilitiesTestModuleLocally.md
  utilities/tools/Test-ModuleLocally.ps1
Labels: documentation

#861 Fix Storage Account MI Issue
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
Labels: bug, [cat] modules

#855 Added an additional note to the wiki to better explain the MSI role assignment
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  docs/wiki/TestingDesign.md
  utilities/pipelines/dependencies/Microsoft.Authorization/roleAssignments/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
Labels: documentation, [cat] testing

#858 Added support for Synapse Private Link Hubs (#856)
  .azuredevops/modulePipelines/ms.synapse.privatelinkhubs.yml
  .github/workflows/ms.synapse.privatelinkhubs.yml
  .vscode/settings.json
  arm/Microsoft.Synapse/privateLinkHubs/.bicep/nested_cuaId.bicep
  arm/Microsoft.Synapse/privateLinkHubs/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Synapse/privateLinkHubs/.bicep/nested_rbac.bicep
  arm/Microsoft.Synapse/privateLinkHubs/.parameters/min.parameters.json
  arm/Microsoft.Synapse/privateLinkHubs/.parameters/parameters.json
  arm/Microsoft.Synapse/privateLinkHubs/deploy.bicep
  arm/Microsoft.Synapse/privateLinkHubs/readme.md
Labels: [cat] modules

#866 Added improved error fetching for failed deployments
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  utilities/pipelines/resourceDeployment/New-ModuleDeployment.ps1
Labels: bug, [cat] pipelines

#872 Align MI outputs
  arm/Microsoft.ApiManagement/service/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.CognitiveServices/accounts/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.ContainerInstance/containerGroups/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.DataFactory/factories/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.Logic/workflows/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/deploy.bicep
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Web/sites/deploy.bicep
Labels: bug, [cat] modules

#874 Specify set of PS modules for different actions
  .azuredevops/pipelineTemplates/module.jobs.deploy.yml
  .azuredevops/pipelineTemplates/module.jobs.publish.yml
  .azuredevops/pipelineTemplates/module.jobs.validate.yml
  .github/actions/templates/publishModule/action.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/actions/templates/validateModulePester/action.yml
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: [cat] pipelines, [cat] azure devops

#846 Implemented dependency pipeline for ADO
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  docs/wiki/KnownIssues.md
  docs/wiki/UtilitiesRegisterAzureDevOpsPipeline.md
  utilities/pipelines/dependencies/Microsoft.ContainerRegistry/registries/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/artifacts.parameters.json
  utilities/tools/AzureDevOps/Register-AzureDevOpsPipeline.ps1
  utilities/tools/AzureDevOps/Set-DevOpsPipelineFile.ps1
Labels: [cat] pipelines, [cat] azure devops

#878 Mapping module deployment outputs to github action output
  .azuredevops/pipelineTemplates/module.jobs.deploy.yml
  .github/actions/templates/validateModuleDeployment/action.yml
Labels: [cat] pipelines, [cat] azure devops

#885 Users/alsehr/881 rsv fix
  arm/Microsoft.RecoveryServices/vaults/.bicep/nested_rbac.bicep
  arm/Microsoft.RecoveryServices/vaults/backupConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupConfig/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/readme.md
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
Labels: bug, [cat] modules

#888 Replace test storage name
  arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
Labels: [cat] modules

#889 Updated error output for Test-AzDeployment
  utilities/pipelines/resourceValidation/Test-TemplateWithParameterFile.ps1
Labels: enhancement, [cat] pipelines

#898 update PIP
  arm/Microsoft.Network/publicIPAddresses/.parameters/parameters.json
  arm/Microsoft.Network/publicIPAddresses/deploy.bicep
  arm/Microsoft.Network/publicIPAddresses/readme.md
Labels: [cat] modules

#875 Update Analysis Service and API Management Outputs
  arm/Microsoft.AnalysisServices/servers/deploy.bicep
  arm/Microsoft.AnalysisServices/servers/readme.md
  arm/Microsoft.ApiManagement/service/.bicep/nested_authorizationServers.bicep
  arm/Microsoft.ApiManagement/service/apiVersionSets/deploy.bicep
  arm/Microsoft.ApiManagement/service/apiVersionSets/readme.md
  arm/Microsoft.ApiManagement/service/apis/deploy.bicep
  arm/Microsoft.ApiManagement/service/apis/policies/deploy.bicep
  arm/Microsoft.ApiManagement/service/apis/policies/readme.md
  arm/Microsoft.ApiManagement/service/apis/readme.md
  arm/Microsoft.ApiManagement/service/authorizationServers/deploy.bicep
  arm/Microsoft.ApiManagement/service/authorizationServers/readme.md
  arm/Microsoft.ApiManagement/service/backends/deploy.bicep
  arm/Microsoft.ApiManagement/service/backends/readme.md
  arm/Microsoft.ApiManagement/service/caches/deploy.bicep
  arm/Microsoft.ApiManagement/service/caches/readme.md
  arm/Microsoft.ApiManagement/service/deploy.bicep
  arm/Microsoft.ApiManagement/service/identityProviders/deploy.bicep
  arm/Microsoft.ApiManagement/service/identityProviders/readme.md
  arm/Microsoft.ApiManagement/service/namedValues/deploy.bicep
  arm/Microsoft.ApiManagement/service/namedValues/readme.md
  arm/Microsoft.ApiManagement/service/policies/deploy.bicep
  arm/Microsoft.ApiManagement/service/policies/readme.md
  arm/Microsoft.ApiManagement/service/portalsettings/deploy.bicep
  arm/Microsoft.ApiManagement/service/portalsettings/readme.md
  arm/Microsoft.ApiManagement/service/products/apis/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/apis/readme.md
  arm/Microsoft.ApiManagement/service/products/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/groups/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/groups/readme.md
  arm/Microsoft.ApiManagement/service/products/readme.md
  arm/Microsoft.ApiManagement/service/readme.md
  arm/Microsoft.ApiManagement/service/subscriptions/deploy.bicep
  arm/Microsoft.ApiManagement/service/subscriptions/readme.md
Labels: enhancement, [cat] modules

#825 Fixed & updated automanage deployment
  arm/Microsoft.Automanage/accounts/.bicep/nested_autoManageAccount.bicep
  arm/Microsoft.Automanage/accounts/.bicep/nested_configurationProfileAssignment.bicep
  arm/Microsoft.Automanage/accounts/.bicep/nested_cuaId.bicep
  arm/Microsoft.Automanage/accounts/.parameters/parameters.json
  arm/Microsoft.Automanage/accounts/deploy.bicep
  arm/Microsoft.Automanage/accounts/readme.md
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_configurationProfileAssignment.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/extensions/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/extensions/readme.md
  arm/Microsoft.Compute/virtualMachines/readme.md
  utilities/pipelines/resourceRemoval/helper/Get-DeploymentTargetResourceList.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Labels: bug, [cat] modules

#904 Enable budget removal
  .azuredevops/modulePipelines/ms.consumption.budgets.yml
  .github/workflows/ms.consumption.budgets.yml
Labels: enhancement, [cat] pipelines, [cat] testing

#896 Update Key vault with security recommendation
  arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
  arm/Microsoft.KeyVault/vaults/secrets/readme.md
Labels: enhancement, [cat] modules

#907 Fix Compute Images
  arm/Microsoft.Compute/images/.parameters/parameters.json
  arm/Microsoft.VirtualMachineImages/imageTemplates/.parameters/parameters.json
Labels: bug, [cat] modules

#901 Add support for Synapse Workspace module
  .azuredevops/modulePipelines/ms.synapse.workspaces.yml
  .github/workflows/ms.synapse.workspaces.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Synapse/privateLinkHubs/readme.md
  arm/Microsoft.Synapse/workspaces/.bicep/nested_cmkRbac.bicep
  arm/Microsoft.Synapse/workspaces/.bicep/nested_cuaId.bicep
  arm/Microsoft.Synapse/workspaces/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Synapse/workspaces/.bicep/nested_rbac.bicep
  arm/Microsoft.Synapse/workspaces/.parameters/basic.parameters.json
  arm/Microsoft.Synapse/workspaces/.parameters/encryptionwsai.parameters.json
  arm/Microsoft.Synapse/workspaces/.parameters/encryptionwuai.parameters.json
  arm/Microsoft.Synapse/workspaces/.parameters/managedvnet.parameters.json
  arm/Microsoft.Synapse/workspaces/.parameters/min.parameters.json
  arm/Microsoft.Synapse/workspaces/deploy.bicep
  arm/Microsoft.Synapse/workspaces/keys/.bicep/nested_cuaId.bicep
  arm/Microsoft.Synapse/workspaces/keys/deploy.bicep
  arm/Microsoft.Synapse/workspaces/keys/readme.md
  arm/Microsoft.Synapse/workspaces/readme.md
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/synapse01.parameters.json
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/synapse02.parameters.json
  utilities/pipelines/resourceValidation/Test-TemplateWithParameterFile.ps1
Labels: [cat] modules

#893 Dependency pipeline Replace msiPrincipalId at runtime
  .azuredevops/pipelineTemplates/module.jobs.deploy.yml
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/workflows/platform.dependencies.yml
  docs/wiki/TestingDesign.md
  utilities/pipelines/dependencies/Microsoft.Authorization/roleAssignments/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/pe.parameters.json
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/sqlmi.parameters.json
  utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
Labels: [cat] pipelines, [cat] github, [cat] azure devops

#912 Updated outputs for namespaces starting with [r], [o]
  arm/Microsoft.OperationalInsights/workspaces/.bicep/nested_solutions.bicep
  arm/Microsoft.OperationalInsights/workspaces/dataSources/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/dataSources/readme.md
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/linkedServices/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/linkedServices/readme.md
  arm/Microsoft.OperationalInsights/workspaces/readme.md
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupConfig/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupPolicies/readme.md
  arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/readme.md
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
  arm/Microsoft.RecoveryServices/vaults/readme.md
  arm/Microsoft.Resources/deploymentScripts/deploy.bicep
  arm/Microsoft.Resources/deploymentScripts/readme.md
  arm/Microsoft.Resources/resourceGroups/.bicep/nested_lock.bicep
  arm/Microsoft.Resources/resourceGroups/deploy.bicep
  arm/Microsoft.Resources/resourceGroups/readme.md
Labels: [cat] modules

#914 Updated outputs for namespace [m], [l], [k], [i]
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Insights/actionGroups/deploy.bicep
  arm/Microsoft.Insights/actionGroups/readme.md
  arm/Microsoft.Insights/activityLogAlerts/deploy.bicep
  arm/Microsoft.Insights/activityLogAlerts/readme.md
  arm/Microsoft.Insights/components/deploy.bicep
  arm/Microsoft.Insights/components/readme.md
  arm/Microsoft.Insights/diagnosticSettings/deploy.bicep
  arm/Microsoft.Insights/diagnosticSettings/readme.md
  arm/Microsoft.Insights/metricAlerts/deploy.bicep
  arm/Microsoft.Insights/metricAlerts/readme.md
  arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
  arm/Microsoft.Insights/privateLinkScopes/readme.md
  arm/Microsoft.Insights/privateLinkScopes/scopedResources/deploy.bicep
  arm/Microsoft.Insights/privateLinkScopes/scopedResources/readme.md
  arm/Microsoft.Insights/scheduledQueryRules/deploy.bicep
  arm/Microsoft.Insights/scheduledQueryRules/readme.md
  arm/Microsoft.KeyVault/vaults/accessPolicies/deploy.bicep
  arm/Microsoft.KeyVault/vaults/accessPolicies/readme.md
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
  arm/Microsoft.KeyVault/vaults/keys/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
  arm/Microsoft.KeyVault/vaults/secrets/readme.md
  arm/Microsoft.Logic/workflows/deploy.bicep
  arm/Microsoft.Logic/workflows/readme.md
  arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
  arm/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
  arm/Microsoft.ManagedIdentity/userAssignedIdentities/readme.md
  arm/Microsoft.ManagedServices/registrationDefinitions/.bicep/nested_registrationAssignment.bicep
  arm/Microsoft.ManagedServices/registrationDefinitions/deploy.bicep
  arm/Microsoft.ManagedServices/registrationDefinitions/readme.md
  arm/Microsoft.Management/managementGroups/deploy.bicep
  arm/Microsoft.Management/managementGroups/readme.md
Labels: [cat] modules

#537 Users/sogangul/bicep service fabric clusters
  .azuredevops/modulePipelines/ms.servicefabric.clusters.yml
  .github/workflows/ms.servicefabric.clusters.yml
  arm/Microsoft.ServiceFabric/clusters/.bicep/nested_cuaId.bicep
  arm/Microsoft.ServiceFabric/clusters/.bicep/nested_rbac.bicep
  arm/Microsoft.ServiceFabric/clusters/.parameters/cert.parameters.json
  arm/Microsoft.ServiceFabric/clusters/.parameters/full.parameters.json
  arm/Microsoft.ServiceFabric/clusters/.parameters/min.parameters.json
  arm/Microsoft.ServiceFabric/clusters/applicationTypes/.bicep/nested_cuaId.bicep
  arm/Microsoft.ServiceFabric/clusters/applicationTypes/deploy.bicep
  arm/Microsoft.ServiceFabric/clusters/applicationTypes/readme.md
  arm/Microsoft.ServiceFabric/clusters/deploy.bicep
  arm/Microsoft.ServiceFabric/clusters/readme.md
Labels: [cat] modules

#926 RSV: Removed unused param from parameter file
  arm/Microsoft.RecoveryServices/vaults/.parameters/parameters.json
Labels: [cat] modules

#930 VNET: Removed requirement for default subnet
  arm/Microsoft.Network/virtualNetworks/.parameters/min.parameters.json
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/readme.md
Labels: [cat] modules

#903 Enabled ManagementGroup-Level removal
  .azuredevops/modulePipelines/ms.management.managementgroups.yml
  .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/workflows/ms.management.managementgroups.yml
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Get-DeploymentTargetResourceList.ps1
  utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsAsFormattedObjectList.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
  utilities/pipelines/resourceValidation/Test-TemplateWithParameterFile.ps1
Labels: bug, [cat] pipelines, [cat] testing

#933 remove unused workflow/pipeline file
  .azuredevops/modulePipelines/ms.automanage.accounts.yml
  .github/workflows/ms.automanage.accounts.yml
Labels: bug, [cat] modules

#939 Users/elanzelm/security eventhub
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.EventHub/namespaces/readme.md
Labels: enhancement

#944 Bug fix for ConvertTo-ARMTemplate
  utilities/tools/ConvertTo-ARMTemplate.ps1
Labels: bug, [cat] pipelines, [cat] modules, [cat] github, [cat] azure devops

#929 Update dependency pipeline with image template and vhd copy
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  docs/wiki/TestingDesign.md
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.VirtualMachineImages/imageTemplates/parameters/parameters.json
Labels: [cat] pipelines

#946 Added union for optional param
  arm/Microsoft.Network/applicationGateways/deploy.bicep
Labels: enhancement, help wanted
