Repository Azure/ResourceModules, pull requests merged in 2022-02, with the labels that each got.

#934 Service Fabric: Fix incorrect parameter file references in pipeline
  .azuredevops/modulePipelines/ms.servicefabric.clusters.yml
  .github/workflows/ms.servicefabric.clusters.yml
Labels: bug, [cat] pipelines

#950 Fix proximityPlacementGroup bug
  arm/Microsoft.Compute/availabilitySets/deploy.bicep
  arm/Microsoft.Compute/availabilitySets/readme.md
Labels: bug

#921 Virtual Hub : Create module
  .azuredevops/modulePipelines/ms.network.virtualHubs.yml
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/ms.network.virtualHubs.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Network/virtualHubs/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/virtualHubs/.parameters/min.parameters.json
  arm/Microsoft.Network/virtualHubs/.parameters/parameters.json
  arm/Microsoft.Network/virtualHubs/deploy.bicep
  arm/Microsoft.Network/virtualHubs/hubRouteTables/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/virtualHubs/hubRouteTables/deploy.bicep
  arm/Microsoft.Network/virtualHubs/hubRouteTables/readme.md
  arm/Microsoft.Network/virtualHubs/hubRouteTables/version.json
  arm/Microsoft.Network/virtualHubs/hubVirtualNetworkConnections/.bicep/nested_cuaId.bicep
  arm/Microsoft.Network/virtualHubs/hubVirtualNetworkConnections/deploy.bicep
  arm/Microsoft.Network/virtualHubs/hubVirtualNetworkConnections/readme.md
  arm/Microsoft.Network/virtualHubs/hubVirtualNetworkConnections/version.json
  arm/Microsoft.Network/virtualHubs/readme.md
  arm/Microsoft.Network/virtualHubs/version.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/7.virtualHubConnection.parameters.json
Labels: [cat] modules

#956 Added token replacement to removal
  utilities/pipelines/resourceRemoval/helper/Get-DependencyResourceNameList.ps1
Labels: bug, [prio] high, [cat] pipelines

#959 API version update
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
  arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress_rbac.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.ContainerRegistry/registries/.bicep/nested_privateEndpoints.bicep
  arm/Microsoft.ContainerRegistry/registries/.bicep/nested_rbac.bicep
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/readme.md
  arm/Microsoft.Network/applicationSecurityGroups/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/applicationSecurityGroups/deploy.bicep
  arm/Microsoft.Network/applicationSecurityGroups/readme.md
  arm/Microsoft.Network/bastionHosts/.bicep/nested_publicIPAddress.bicep
  arm/Microsoft.Network/bastionHosts/.bicep/nested_publicIPAddress_rbac.bicep
  arm/Microsoft.Network/bastionHosts/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/bastionHosts/deploy.bicep
  arm/Microsoft.Network/bastionHosts/readme.md
  arm/Microsoft.Network/connections/deploy.bicep
  arm/Microsoft.Network/connections/readme.md
  arm/Microsoft.Network/ddosProtectionPlans/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/ddosProtectionPlans/deploy.bicep
  arm/Microsoft.Network/ddosProtectionPlans/readme.md
  arm/Microsoft.Network/expressRouteCircuits/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/expressRouteCircuits/deploy.bicep
  arm/Microsoft.Network/expressRouteCircuits/readme.md
  arm/Microsoft.Network/ipGroups/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/ipGroups/deploy.bicep
  arm/Microsoft.Network/ipGroups/readme.md
  arm/Microsoft.Network/loadBalancers/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/loadBalancers/backendAddressPools/deploy.bicep
  arm/Microsoft.Network/loadBalancers/deploy.bicep
  arm/Microsoft.Network/loadBalancers/inboundNatRules/deploy.bicep
  arm/Microsoft.Network/loadBalancers/readme.md
  arm/Microsoft.Network/localNetworkGateways/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/localNetworkGateways/deploy.bicep
  arm/Microsoft.Network/localNetworkGateways/readme.md
  arm/Microsoft.Network/natGateways/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/natGateways/deploy.bicep
  arm/Microsoft.Network/natGateways/readme.md
  arm/Microsoft.Network/networkSecurityGroups/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/readme.md
  arm/Microsoft.Network/networkWatchers/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/networkWatchers/deploy.bicep
  arm/Microsoft.Network/networkWatchers/readme.md
  arm/Microsoft.Network/publicIPAddresses/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/publicIPPrefixes/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/publicIPPrefixes/deploy.bicep
  arm/Microsoft.Network/publicIPPrefixes/readme.md
  arm/Microsoft.Network/routeTables/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/routeTables/deploy.bicep
  arm/Microsoft.Network/routeTables/readme.md
  arm/Microsoft.Network/virtualNetworkGateways/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
  arm/Microsoft.Network/virtualNetworkGateways/readme.md
Labels: [cat] modules, [cat] testing

#979 Incomplete title on wiki home
  docs/wiki/Home.md
Labels: bug, documentation

#976 Added missing ADO pipeline for disks
  .azuredevops/modulePipelines/ms.compute.disks.yml
Labels: bug, [prio] medium, [cat] pipelines, [cat] modules, [cat] azure devops

#975 Fix publishing template for firewall policies in ADO
  .azuredevops/modulePipelines/ms.network.firewallpolicies.yml
Labels: bug, [prio] medium, [cat] pipelines, [cat] modules, [cat] publishing, [cat] azure devops

#972 Introduce grouping of logs
  .azuredevops/pipelineTemplates/jobs.publishModule.yml
  .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
  .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
  .github/actions/templates/getWorkflowInput/action.yml
  .github/actions/templates/publishModule/action.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/actions/templates/validateModulePester/action.yml
Labels: [cat] pipelines, [cat] github, [cat] azure devops

#980 vm adp token and description fix
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.Network/networkWatchers/.parameters/parameters.json
  utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
Labels: [cat] testing

#985 Fixed both Load Balancer & AKS
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
  arm/Microsoft.Network/loadBalancers/.parameters/min.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/publicIPAddresses/parameters/lb.min.parameters.json
Labels: bug, [cat] modules

#986 Trigger all pipelines after environment cleanup
  arm/Microsoft.Compute/diskEncryptionSets/.parameters/parameters.json
  arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.min.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
  arm/Microsoft.Sql/managedInstances/.parameters/parameters.json
  docs/wiki/GettingStarted.md
  settings.json
  utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
Labels: [cat] testing

#987 Quick fix for Local Test Script and Documentation
  docs/wiki/TestingUsage.md
  utilities/tools/Test-ModuleLocally.ps1
Labels: bug

#1013 Updated TS example
  docs/wiki/ModulesUsage.md
Labels: documentation

#947 Updated Compute resources with security recommendations
  arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
  arm/Microsoft.Compute/diskEncryptionSets/readme.md
  arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
  constructs/Microsoft.Authorization/roleAssignments-multiRolesMultiPrincipals/readme.md
Labels: [cat] modules

#1022 Keyvaults - Securing secrets parameter by using object
  arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.KeyVault/vaults/readme.md
Labels: [prio] high, [cat] modules

#1026 Rewrite of the AppGW module
  arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
  arm/Microsoft.Network/applicationGateways/deploy.bicep
  arm/Microsoft.Network/applicationGateways/readme.md
  arm/Microsoft.Network/applicationGateways/version.json
Labels: [cat] modules

#1030 Simplify VM availability zone parameters
  arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
  arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: enhancement, [cat] modules

#978 Publish: Cascading version update
  .azuredevops/pipelineTemplates/jobs.publishModule.yml
  .github/actions/templates/publishModule/action.yml
  docs/wiki/PipelinesDesign.md
  utilities/pipelines/resourcePublish/Get-ModulesToPublish.ps1
  utilities/pipelines/resourcePublish/Publish-ModuleToUniversalArtifactFeed.ps1
Labels: [prio] medium, [cat] pipelines, [cat] modules, [cat] publishing, [cat] github, [cat] azure devops

#1051 Wiki restructuring - empty side by side toc
  docs/wiki/Contribution guide - Generate module readme.md
  docs/wiki/Contribution guide - Get formatted RBAC roles.md
  docs/wiki/Contribution guide.md
  docs/wiki/Getting started - Dependency pipeline.md
  docs/wiki/Getting started - Prerequisites.md
  docs/wiki/Getting started - Setup environment.md
  docs/wiki/Getting started - Token replacement.md
  docs/wiki/Getting started.md
  docs/wiki/Home.md
  docs/wiki/Interoperability - Bicep to ARM conversion.md
  docs/wiki/Interoperability - Register ADO pipelines.md
  docs/wiki/Interoperability.md
  docs/wiki/Known issues.md
  docs/wiki/The CI environment - Deployment validation.md
  docs/wiki/The CI environment - Pipeline design.md
  docs/wiki/The CI environment - Pipeline usage.md
  docs/wiki/The CI environment - Publishing.md
  docs/wiki/The CI environment - Static validation.md
  docs/wiki/The CI environment.md
  docs/wiki/The context - CARML overview.md
  docs/wiki/The context - IaC.md
  docs/wiki/The context.md
  docs/wiki/The library - Module design.md
  docs/wiki/The library - Module usage.md
  docs/wiki/The library.md
Labels: documentation

#1037 Fix incorrect parameter handling in Automation Account
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
Labels: bug, [cat] modules

#1053 Align all nested_privateEndpoint to the same API version
  arm/Microsoft.Automation/automationAccounts/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.EventHub/namespaces/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.EventHub/namespaces/readme.md
  arm/Microsoft.Insights/privateLinkScopes/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Insights/privateLinkScopes/readme.md
  arm/Microsoft.Network/privateEndpoints/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateEndpoints/deploy.bicep
  arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
  arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/readme.md
  arm/Microsoft.Network/privateEndpoints/readme.md
  arm/Microsoft.Synapse/privateLinkHubs/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Synapse/privateLinkHubs/readme.md
  arm/Microsoft.Web/sites/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Web/sites/readme.md
  docs/wiki/ModulesDesign.md
  utilities/pipelines/dependencies/Microsoft.Automation/automationAccounts/parameters/law.parameters.json
Labels: [cat] modules

#1043 Resource Removal: Add resource Group support for mg level deployments
  utilities/pipelines/resourceRemoval/helper/Get-DeploymentTargetResourceList.ps1
Labels: bug, [prio] high
