Repository Azure/ResourceModules, pull requests merged in 2022-05, with the labels that each got.

#1348 Added configuration options to Microsoft.Batch/batchAccounts
  .azuredevops/modulePipelines/ms.batch.batchaccounts.yml
  arm/Microsoft.Batch/batchAccounts/.parameters/min.parameters.json
  arm/Microsoft.Batch/batchAccounts/.parameters/parameters.json
  arm/Microsoft.Batch/batchAccounts/deploy.bicep
  arm/Microsoft.Batch/batchAccounts/readme.md
Labels: enhancement, [cat] modules

#1344 Add RBAC to Private DNS records
  arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
  arm/Microsoft.Network/privateDnsZones/A/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/A/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/A/readme.md
  arm/Microsoft.Network/privateDnsZones/A/version.json
  arm/Microsoft.Network/privateDnsZones/AAAA/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/AAAA/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/AAAA/readme.md
  arm/Microsoft.Network/privateDnsZones/AAAA/version.json
  arm/Microsoft.Network/privateDnsZones/CNAME/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/CNAME/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/CNAME/readme.md
  arm/Microsoft.Network/privateDnsZones/CNAME/version.json
  arm/Microsoft.Network/privateDnsZones/MX/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/MX/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/MX/readme.md
  arm/Microsoft.Network/privateDnsZones/MX/version.json
  arm/Microsoft.Network/privateDnsZones/PTR/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/PTR/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/PTR/readme.md
  arm/Microsoft.Network/privateDnsZones/PTR/version.json
  arm/Microsoft.Network/privateDnsZones/SOA/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/SOA/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/SOA/readme.md
  arm/Microsoft.Network/privateDnsZones/SOA/version.json
  arm/Microsoft.Network/privateDnsZones/SRV/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/SRV/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/SRV/readme.md
  arm/Microsoft.Network/privateDnsZones/SRV/version.json
  arm/Microsoft.Network/privateDnsZones/TXT/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/privateDnsZones/TXT/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/TXT/readme.md
  arm/Microsoft.Network/privateDnsZones/TXT/version.json
  arm/Microsoft.Network/privateDnsZones/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/version.json
Labels: enhancement, [cat] modules

#1345 Add aks agic addon to managedCluster (AKS)
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
  arm/Microsoft.ContainerService/managedClusters/version.json
Labels: enhancement, [cat] modules

#1343 Added role assignment removal to removal logic
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
Labels: enhancement, [cat] pipelines

#1359 Update ML Workspace to latest API
  .azuredevops/modulePipelines/ms.machinelearningservices.workspaces.yml
  arm/Microsoft.MachineLearningServices/workspaces/.parameters/min.parameters.json
  arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
  arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Sql/managedInstances/readme.md
Labels: enhancement, [cat] modules

#1361 allowed User assigned identity deployments
  arm/Microsoft.Authorization/policyAssignments/.parameters/rg.min.parameters.json
  arm/Microsoft.Authorization/policyAssignments/.parameters/rg.parameters.json
  arm/Microsoft.Authorization/policyAssignments/.parameters/sub.parameters.json
  arm/Microsoft.Authorization/policyAssignments/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/managementGroup/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/managementGroup/readme.md
  arm/Microsoft.Authorization/policyAssignments/readme.md
  arm/Microsoft.Authorization/policyAssignments/resourceGroup/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/resourceGroup/readme.md
  arm/Microsoft.Authorization/policyAssignments/subscription/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/subscription/readme.md
Labels: enhancement

#1366 Fix Set-ModuleReadMe when called w/ relative path
  utilities/tools/Set-ModuleReadMe.ps1
Labels: enhancement

#1369 [Modules] Added multiple vm deployment example
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
  constructs/Microsoft.Compute/virtualMachinesMultiple/.parameters/linux.prefix.parameter.json
  constructs/Microsoft.Compute/virtualMachinesMultiple/.parameters/linux.vmnames.parameter.json
  constructs/Microsoft.Compute/virtualMachinesMultiple/deploy.bicep
  constructs/Microsoft.Compute/virtualMachinesMultiple/readme.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: [cat] samples

#1374 [Modules] Added SQL Server Vulnerability Assessments
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/readme.md
  arm/Microsoft.Sql/servers/vulnerabilityAssessments/deploy.bicep
  arm/Microsoft.Sql/servers/vulnerabilityAssessments/readme.md
  arm/Microsoft.Sql/servers/vulnerabilityAssessments/version.json
Labels: enhancement

#1365 [Modules] VirtualMachine: Configure boot diagnostics with managed storage account
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/readme.md
Labels: [cat] modules

#1373 [Static Validation] Pester structural tests
  arm/.global/global.module.tests.ps1
  docs/wiki/Getting started - Scenario 1 Onboard module library and CI environment.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: [cat] testing

#1367 [Modules] SQL-Server: Added private endpoint
  arm/Microsoft.Sql/servers/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.Sql/servers/.parameters/parameters.json
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/readme.md
Labels: enhancement, [cat] modules

#1398 [Modules] allow 0 as min capacity
  arm/Microsoft.Network/applicationGateways/deploy.bicep
Labels: [cat] modules

#1389 [CI environment] Set Az Context in Removal Stage in ADO
  .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
Labels: [cat] pipelines

#1408 [Bugfix] Added missing output to tags module
  arm/Microsoft.Resources/tags/deploy.bicep
  arm/Microsoft.Resources/tags/readme.md
  arm/Microsoft.Resources/tags/resourceGroups/deploy.bicep
  arm/Microsoft.Resources/tags/resourceGroups/readme.md
  arm/Microsoft.Resources/tags/subscriptions/deploy.bicep
  arm/Microsoft.Resources/tags/subscriptions/readme.md
Labels: bug, [cat] modules

#1406 [Module] Fixed Inconsistent naming of NSGs IDs #1323
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
Labels: enhancement, [cat] modules

#1393 Added telemetry to AAD module & description to docs
  .github/PULL_REQUEST_TEMPLATE.md
  arm/Microsoft.AAD/DomainServices/deploy.bicep
  arm/Microsoft.AAD/DomainServices/readme.md
  docs/wiki/The library - Module design.md
  settings.json
Labels: documentation

#1414 VMSS add Condition to EncryptionAtHost
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
Labels: bug, [cat] modules

#1411 update Recovery Services Vault API to latest
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/readme.md
Labels: enhancement, [cat] modules

#1404 [Module] App Configuration Stores
  .azuredevops/modulePipelines/ms.appconfiguration.configurationstores.yml
  .github/workflows/ms.appconfiguration.configurationstores.yml
  README.md
  arm/Microsoft.AppConfiguration/configurationStores/.bicep/nested_rbac.bicep
  arm/Microsoft.AppConfiguration/configurationStores/.parameters/min.parameters.json
  arm/Microsoft.AppConfiguration/configurationStores/.parameters/parameters.json
  arm/Microsoft.AppConfiguration/configurationStores/deploy.bicep
  arm/Microsoft.AppConfiguration/configurationStores/readme.md
  arm/Microsoft.AppConfiguration/configurationStores/version.json
  utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
Labels: enhancement, [cat] modules

#1400 [NetworkInterface] Added module
  .azuredevops/modulePipelines/ms.network.networkinterfaces.yml
  .github/workflows/ms.network.networkinterfaces.yml
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Network/networkInterfaces/.bicep/nested_rbac.bicep
  arm/Microsoft.Network/networkInterfaces/.parameters/min.parameters.json
  arm/Microsoft.Network/networkInterfaces/.parameters/parameters.json
  arm/Microsoft.Network/networkInterfaces/deploy.bicep
  arm/Microsoft.Network/networkInterfaces/readme.md
  arm/Microsoft.Network/networkInterfaces/version.json
  arm/Microsoft.Sql/servers/databases/deploy.bicep
  arm/Microsoft.Sql/servers/databases/readme.md
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Sql/servers/firewallRules/deploy.bicep
  arm/Microsoft.Sql/servers/firewallRules/readme.md
  arm/Microsoft.Sql/servers/readme.md
  arm/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
  arm/Microsoft.Sql/servers/securityAlertPolicies/readme.md
Labels: [cat] modules

#1419 [Static validation] Fixing ending dots for parameter descriptions
  arm/Microsoft.Authorization/roleAssignments/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/managementGroup/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/managementGroup/readme.md
  arm/Microsoft.Authorization/roleAssignments/readme.md
  arm/Microsoft.Authorization/roleAssignments/resourceGroup/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/resourceGroup/readme.md
  arm/Microsoft.Authorization/roleAssignments/subscription/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/subscription/readme.md
  arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/readme.md
  arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
  arm/Microsoft.MachineLearningServices/workspaces/readme.md
  arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
  arm/Microsoft.NetApp/netAppAccounts/readme.md
  arm/Microsoft.Network/bastionHosts/.bicep/nested_publicIPAddress.bicep
  arm/Microsoft.Network/privateDnsZones/A/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/A/readme.md
  arm/Microsoft.Network/privateDnsZones/AAAA/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/AAAA/readme.md
  arm/Microsoft.Network/privateDnsZones/CNAME/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/CNAME/readme.md
  arm/Microsoft.Network/privateDnsZones/MX/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/MX/readme.md
  arm/Microsoft.Network/privateDnsZones/PTR/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/PTR/readme.md
  arm/Microsoft.Network/privateDnsZones/SOA/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/SOA/readme.md
  arm/Microsoft.Network/privateDnsZones/SRV/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/SRV/readme.md
  arm/Microsoft.Network/privateDnsZones/TXT/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/TXT/readme.md
  constructs/Microsoft.Compute/virtualMachinesMultiple/deploy.bicep
  docs/wiki/The library - Module design.md
Labels: documentation, [cat] modules, [cat] testing

#1412 [Modules] update parameter paths of Deployment Scripts
  .azuredevops/modulePipelines/ms.resources.deploymentscripts.yml
Labels: bug, [cat] pipelines, [cat] azure devops

#1420 [Static validation] Fixing ending dots for parameter descriptions continued
  arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/managementGroup/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/managementGroup/readme.md
  arm/Microsoft.Authorization/policySetDefinitions/readme.md
  arm/Microsoft.Authorization/policySetDefinitions/subscription/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/subscription/readme.md
  arm/Microsoft.Authorization/roleAssignments/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/managementGroup/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/managementGroup/readme.md
  arm/Microsoft.Authorization/roleAssignments/readme.md
  arm/Microsoft.Authorization/roleAssignments/resourceGroup/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/resourceGroup/readme.md
  arm/Microsoft.Authorization/roleAssignments/subscription/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/subscription/readme.md
  arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
  arm/Microsoft.NetApp/netAppAccounts/readme.md
Labels: documentation, [cat] modules, [cat] testing

#1413 [Modules] OperationalInsights add etag parameter to SavedSearches
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
Labels: enhancement, [cat] modules

#1418 [Modules] [AppConfig] Added private endpoint
  arm/Microsoft.AppConfiguration/configurationStores/.bicep/nested_privateEndpoint.bicep
  arm/Microsoft.AppConfiguration/configurationStores/.parameters/parameters.json
  arm/Microsoft.AppConfiguration/configurationStores/deploy.bicep
  arm/Microsoft.AppConfiguration/configurationStores/readme.md
Labels: enhancement, [cat] modules

#1423 [Module] Renamed parameter to more meaningful name
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/readme.md
Labels: enhancement, [cat] modules

#1426 [Testing] Implemented purge for AppConfiguration
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourcePostRemoval.ps1
Labels: enhancement, [cat] testing

#1422 [Pipeline] Updated conditions for ADO dependency pipeline
  .azuredevops/platformPipelines/platform.dependencies.yml
Labels: bug, [cat] pipelines, [cat] azure devops

#1427 [Static Validation] Add Pester test for conditional parameters description
  arm/.global/global.module.tests.ps1
Labels: enhancement, [cat] testing

#1437 [Modules] Changed telemetry implementation to only deploy a single PID
  arm/Microsoft.ApiManagement/service/apis/deploy.bicep
  arm/Microsoft.ApiManagement/service/deploy.bicep
  arm/Microsoft.ApiManagement/service/products/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/deploy.bicep
  arm/Microsoft.Authorization/policyAssignments/readme.md
  arm/Microsoft.Authorization/policyDefinitions/deploy.bicep
  arm/Microsoft.Authorization/policyExemptions/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
  arm/Microsoft.Authorization/roleAssignments/deploy.bicep
  arm/Microsoft.Authorization/roleDefinitions/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.Compute/galleries/deploy.bicep
  arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
  arm/Microsoft.Compute/virtualMachines/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.DataFactory/factories/deploy.bicep
  arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/deploy.bicep
  arm/Microsoft.EventHub/namespaces/deploy.bicep
  arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
  arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
  arm/Microsoft.KeyVault/vaults/deploy.bicep
  arm/Microsoft.NetApp/netAppAccounts/capacityPools/deploy.bicep
  arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
  arm/Microsoft.Network/firewallPolicies/deploy.bicep
  arm/Microsoft.Network/loadBalancers/deploy.bicep
  arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
  arm/Microsoft.Network/networkWatchers/deploy.bicep
  arm/Microsoft.Network/privateDnsZones/deploy.bicep
  arm/Microsoft.Network/privateEndpoints/deploy.bicep
  arm/Microsoft.Network/virtualHubs/deploy.bicep
  arm/Microsoft.Network/virtualNetworks/deploy.bicep
  arm/Microsoft.Network/vpnGateways/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/replicationFabrics/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/deploy.bicep
  arm/Microsoft.Resources/tags/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/queues/deploy.bicep
  arm/Microsoft.ServiceBus/namespaces/topics/deploy.bicep
  arm/Microsoft.ServiceFabric/clusters/deploy.bicep
  arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
  arm/Microsoft.Sql/managedInstances/deploy.bicep
  arm/Microsoft.Sql/servers/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/containers/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
  arm/Microsoft.Web/sites/deploy.bicep
  constructs/Microsoft.Compute/virtualMachinesMultiple/deploy.bicep
  docs/wiki/The library - Module design.md
Labels: enhancement, [cat] modules

#1392 [Modules] 1154 Add Public IP to Azure Firewall
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Network/azureFirewalls/.bicep/nested_publicIPAddress.bicep
  arm/Microsoft.Network/azureFirewalls/.bicep/nested_publicIPAddress_rbac.bicep
  arm/Microsoft.Network/azureFirewalls/.parameters/addpip.parameters.json
  arm/Microsoft.Network/azureFirewalls/.parameters/custompip.parameters.json
  arm/Microsoft.Network/azureFirewalls/.parameters/min.parameters.json
  arm/Microsoft.Network/azureFirewalls/.parameters/parameters.json
  arm/Microsoft.Network/azureFirewalls/deploy.bicep
  arm/Microsoft.Network/azureFirewalls/readme.md
  docs/wiki/The library - Module design.md
  utilities/pipelines/dependencies/Microsoft.Network/publicIPAddresses/parameters/fw.additional.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/10.azfw.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/11.azfw.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/9.azfw.parameters.json
Labels: enhancement, [cat] modules

#1438 [Static validation] evh missing description dot
  arm/Microsoft.EventHub/namespaces/networkRuleSets/deploy.bicep
  arm/Microsoft.EventHub/namespaces/networkRuleSets/readme.md
Labels: bug, [cat] modules, [cat] testing

#1439 [ReadMe] Fixed KeyVault reference for Bicep example in ReadMes
  arm/Microsoft.AAD/DomainServices/readme.md
  arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.Network/connections/readme.md
  arm/Microsoft.Sql/managedInstances/readme.md
  arm/Microsoft.Sql/servers/readme.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: bug, documentation, [cat] modules

#1375 [Docs]: Updated solution examples in Wiki
  docs/wiki/Solution creation.md
Labels: documentation

#1449 [Pipeline] Updated removal script to restore tokens
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/fa.parameters.json
  utilities/pipelines/dependencies/Microsoft.Storage/storageAccounts/parameters/law.parameters.json
  utilities/pipelines/resourceRemoval/helper/Get-DependencyResourceNameList.ps1
Labels: [cat] pipelines
