Repository Azure/ResourceModules, pull requests merged in 2022-06, with the labels that each got.

#1456 [Platform] Created Issue-Assignment pipeline
  .github/workflows/platform.issueAssignment.yml
Labels: [cat] pipelines, [cat] github

#1464 Fix typo in global test
  arm/.global/global.module.tests.ps1
Labels: bug

#1480 Updated parameters description to fix failed Pester tests
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/protectedItems/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/protectedItems/readme.md
Labels: bug, [cat] modules

#1476 [Pipelines] Workaround for Az CLI bug + regenerated docs with fix #1471
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Automation/automationAccounts/.parameters/encr.parameters.json
  arm/Microsoft.Compute/virtualMachines/readme.md
  arm/Microsoft.EventHub/namespaces/readme.md
  arm/Microsoft.KeyVault/vaults/readme.md
  arm/Microsoft.ServiceBus/namespaces/readme.md
  utilities/tools/Set-ModuleReadMe.ps1
Labels: bug, [prio] high, [cat] pipelines

#1448 [Module] Fix pipeline errors
  .azuredevops/modulePipelines/ms.web.hostingenvironments.yml
  arm/.global/global.module.tests.ps1
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.ContainerService/managedClusters/deploy.bicep
  arm/Microsoft.ContainerService/managedClusters/readme.md
  arm/Microsoft.DesktopVirtualization/hostpools/.parameters/parameters.json
  arm/Microsoft.DesktopVirtualization/hostpools/readme.md
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
  arm/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
  arm/Microsoft.Security/azureSecurityCenter/deploy.bicep
  arm/Microsoft.Security/azureSecurityCenter/readme.md
  arm/Microsoft.Web/hostingEnvironments/.parameters/asev2.parameters.json
  arm/Microsoft.Web/hostingEnvironments/.parameters/asev3.parameters.json
  arm/Microsoft.Web/hostingEnvironments/deploy.bicep
  arm/Microsoft.Web/hostingEnvironments/readme.md
  utilities/pipelines/dependencies/Microsoft.Network/networkSecurityGroups/parameters/ase.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/parameters.json
Labels: bug, [cat] modules

#1397 [Modules] webhooks for ACR
  arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/readme.md
  arm/Microsoft.ContainerRegistry/registries/webhooks/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/webhooks/readme.md
  arm/Microsoft.ContainerRegistry/registries/webhooks/version.json
Labels: enhancement, [cat] modules

#1431 [Modules] Implemented CMK for Storage Account
  .azuredevops/modulePipelines/ms.storage.storageaccounts.yml
  arm/Microsoft.Storage/storageAccounts/.parameters/encr.parameters.json
  arm/Microsoft.Storage/storageAccounts/deploy.bicep
  arm/Microsoft.Storage/storageAccounts/readme.md
Labels: enhancement, [cat] modules

#1491 [CI environment] Cleanup outdated custom removal logic for VWan
  docs/wiki/The CI environment - Deployment validation.md
  utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
Labels: documentation, [cat] pipelines, [cat] testing

#1485 [Modules] Formatted Automation Account parameter files
  arm/Microsoft.Automation/automationAccounts/.parameters/encr.parameters.json
  arm/Microsoft.Automation/automationAccounts/readme.md
Labels: enhancement, [cat] modules

#1451 [GitHub, CI] Update GitHub Workflows to use Azure/PowerShell action
  .github/actions/templates/publishModule/action.yml
  .github/actions/templates/validateModuleDeployment/action.yml
  .github/actions/templates/validateModulePester/action.yml
  .github/workflows/platform.dependencies.yml
Labels: [cat] pipelines, [cat] github

#1494 [Modules] Cross referencing linkedServices module in automationAccount
  arm/Microsoft.Automation/automationAccounts/.bicep/nested_linkedService.bicep
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.OperationalInsights/workspaces/linkedServices/deploy.bicep
Labels: enhancement, [cat] modules

#1462 [Testing] Reworked tests to not use HTML & shared functions
  arm/.global/global.module.tests.ps1
  arm/.global/shared/helper.psm1
Labels: enhancement, [cat] testing

#1470 [Modules] Update PolicySet Definition Name limit to 64
  arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/managementGroup/deploy.bicep
  arm/Microsoft.Authorization/policySetDefinitions/managementGroup/readme.md
  arm/Microsoft.Authorization/policySetDefinitions/readme.md
Labels: enhancement, [cat] modules

#1482 [Testing] Updated tests to better handle resources that don't have standard outputs + updated 'skip' behavior + fixed Pester test result reference + fixed readme param name
  .github/actions/templates/validateModulePester/action.yml
  arm/.global/global.module.tests.ps1
  utilities/tools/Set-ModuleReadMe.ps1
Labels: bug, enhancement, [cat] testing

#1507 [Bug] Added principalType to RSV param
  utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
Labels: bug

#1506 Users/jontreynes/1441 bhostspip
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Network/bastionHosts/.parameters/addpip.parameters.json
  arm/Microsoft.Network/bastionHosts/.parameters/custompip.parameters.json
  arm/Microsoft.Network/bastionHosts/.parameters/parameters.json
  arm/Microsoft.Network/bastionHosts/deploy.bicep
  arm/Microsoft.Network/bastionHosts/readme.md
  utilities/pipelines/dependencies/Microsoft.Network/publicIPAddresses/parameters/bas.additional.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/12.bastion.parameters.json
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/13.bastion.parameters.json
Labels: enhancement, [cat] modules

#1497 Fixed ApplicationGateway pipeline deployment by updating the keyvault reference.
  arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
  arm/Microsoft.Network/applicationGateways/readme.md
Labels: enhancement, [cat] modules

#1481 [Pipeline] Improve runtime of `Set-EnvironmentOnAgent` script
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: enhancement, [cat] pipelines

#1505 [Testing] Switching Pester task back to AzPowerShell + Simplifying pipeline
  .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
  .github/actions/templates/validateModulePester/action.yml
Labels: bug, [prio] high, [cat] pipelines, [cat] testing, [cat] github, [cat] azure devops

#1508 [Testing] Fixed incorrect API test reference & env-value propagation
  arm/.global/global.module.tests.ps1
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: bug, [prio] high, [cat] testing

#1509 Fixed pipeline name parsing in Register-AzureDevOpsPipeline.ps1
  utilities/tools/AzureDevOps/Register-AzureDevOpsPipeline.ps1
Labels: enhancement

#1486 [Testing] Expanded Pester test output
  arm/.global/global.module.tests.ps1
Labels: [cat] testing

#1496 New module Microsoft.DataProtection.Backupvaults added
  .azuredevops/modulePipelines/ms.dataprotection.backupvaults.yml
  .github/workflows/ms.dataprotection.backupvaults.yml
  arm/Microsoft.DataProtection/backupVaults/.bicep/nested_rbac.bicep
  arm/Microsoft.DataProtection/backupVaults/.parameters/min.parameters.json
  arm/Microsoft.DataProtection/backupVaults/.parameters/parameters.json
  arm/Microsoft.DataProtection/backupVaults/backupPolicies/deploy.bicep
  arm/Microsoft.DataProtection/backupVaults/backupPolicies/readme.md
  arm/Microsoft.DataProtection/backupVaults/backupPolicies/version.json
  arm/Microsoft.DataProtection/backupVaults/deploy.bicep
  arm/Microsoft.DataProtection/backupVaults/readme.md
  arm/Microsoft.DataProtection/backupVaults/version.json
Labels: enhancement, [cat] pipelines, [cat] modules

#1522 [CI Environment] Extend agent setup to be more robust
  .azuredevops/pipelineTemplates/jobs.publishModule.yml
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: bug, [cat] pipelines

#1515 [CI Environment] Fixed lock removal + added error handling in case no deployment resource if found
  utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
  utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Labels: bug, [cat] pipelines, [cat] testing

#1511 [Modules] Create solutions module and cross reference in workspace and automation account
  .azuredevops/modulePipelines/ms.operationsmanagement.solutions.yml
  .github/workflows/ms.operationsmanagement.solutions.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Automation/automationAccounts/.bicep/nested_solution.bicep
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  arm/Microsoft.Automation/automationAccounts/deploy.bicep
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.OperationalInsights/workspaces/.bicep/nested_solutions.bicep
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/readme.md
  arm/Microsoft.OperationsManagement/solutions/.parameters/min.parameters.json
  arm/Microsoft.OperationsManagement/solutions/.parameters/ms.parameters.json
  arm/Microsoft.OperationsManagement/solutions/.parameters/nonms.parameters.json
  arm/Microsoft.OperationsManagement/solutions/deploy.bicep
  arm/Microsoft.OperationsManagement/solutions/readme.md
  arm/Microsoft.OperationsManagement/solutions/version.json
  utilities/pipelines/dependencies/Microsoft.OperationalInsights/workspaces/parameters/sol.parameters.json
Labels: enhancement, [cat] modules

#1528 [Wiki] Update wiki with required GH settings for CI environment run
  docs/wiki/Getting started - Scenario 1 Onboard module library and CI environment.md
  docs/wiki/media/SetupEnvironment/workflow_permissions.png
Labels: documentation

#1530 [Modules] Fix Automation Account and Log Analytics Workspace
  arm/Microsoft.Automation/automationAccounts/.parameters/encr.parameters.json
  arm/Microsoft.Automation/automationAccounts/.parameters/min.parameters.json
  arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
  arm/Microsoft.Automation/automationAccounts/readme.md
  arm/Microsoft.OperationalInsights/workspaces/.parameters/min.parameters.json
  arm/Microsoft.OperationalInsights/workspaces/.parameters/parameters.json
  arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
  arm/Microsoft.OperationalInsights/workspaces/readme.md
  utilities/pipelines/dependencies/Microsoft.Automation/automationAccounts/parameters/parameters.json
Labels: bug, [cat] modules

#1529 [Modules] Compute Galleries API version update
  arm/Microsoft.Compute/galleries/.bicep/nested_roleAssignments.bicep
  arm/Microsoft.Compute/galleries/deploy.bicep
  arm/Microsoft.Compute/galleries/images/.bicep/nested_roleAssignments.bicep
  arm/Microsoft.Compute/galleries/images/deploy.bicep
  arm/Microsoft.Compute/galleries/images/readme.md
  arm/Microsoft.Compute/galleries/readme.md
Labels: bug, [cat] modules

#1542 [Modules] Remove RBAC capabilities from ManagementGroup module
  arm/Microsoft.Management/managementGroups/.bicep/nested_roleAssignments.bicep
  arm/Microsoft.Management/managementGroups/.parameters/parameters.json
  arm/Microsoft.Management/managementGroups/deploy.bicep
  arm/Microsoft.Management/managementGroups/readme.md
Labels: bug, [cat] modules

#1544 [Wiki] Management Group module known issues
  docs/wiki/Known issues.md
Labels: documentation, enhancement

#1540 [Modules] Storage Account minor update to param example in networkAcls.
  arm/Microsoft.Storage/storageAccounts/readme.md
Labels: enhancement, [cat] modules

#1549 [Modules] Azure Firewall cross referencing PIP
  arm/Microsoft.Network/azureFirewalls/.bicep/nested_publicIPAddress.bicep
  arm/Microsoft.Network/azureFirewalls/.bicep/nested_publicIPAddress_rbac.bicep
  arm/Microsoft.Network/azureFirewalls/deploy.bicep
Labels: enhancement, [cat] modules

#1548 [Modules] Disk Encryption Sets cross referencing KV access policies
  arm/Microsoft.Compute/diskEncryptionSets/.bicep/nested_kvAccessPolicy.bicep
  arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
Labels: enhancement, [cat] modules

#1537 [Modules] Container registry updated default value
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
Labels: enhancement, [cat] modules

#1552 [Modules] Revert encryption default value and update container registry readme
  arm/Microsoft.ContainerRegistry/registries/deploy.bicep
  arm/Microsoft.ContainerRegistry/registries/readme.md
Labels: bug, [cat] modules

#1547 [Modules] Lock module and cross reference from RG
  .azuredevops/modulePipelines/ms.authorization.locks.yml
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/ms.authorization.locks.yml
  .github/workflows/platform.dependencies.yml
  arm/Microsoft.Authorization/locks/.parameters/rg.parameters.json
  arm/Microsoft.Authorization/locks/deploy.bicep
  arm/Microsoft.Authorization/locks/readme.md
  arm/Microsoft.Authorization/locks/resourceGroup/deploy.bicep
  arm/Microsoft.Authorization/locks/resourceGroup/readme.md
  arm/Microsoft.Authorization/locks/resourceGroup/version.json
  arm/Microsoft.Authorization/locks/subscription/deploy.bicep
  arm/Microsoft.Authorization/locks/subscription/readme.md
  arm/Microsoft.Authorization/locks/subscription/version.json
  arm/Microsoft.Authorization/locks/version.json
  arm/Microsoft.Resources/resourceGroups/.bicep/nested_lock.bicep
  arm/Microsoft.Resources/resourceGroups/deploy.bicep
  utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/locks.parameters.json
Labels: enhancement, [cat] modules

#1559 [Modules] Fix locks output scope
  arm/Microsoft.Authorization/locks/deploy.bicep
  arm/Microsoft.Authorization/locks/resourceGroup/deploy.bicep
  arm/Microsoft.Authorization/locks/resourceGroup/readme.md
  arm/Microsoft.Authorization/locks/subscription/deploy.bicep
  arm/Microsoft.Authorization/locks/subscription/readme.md
Labels: bug, [cat] modules

#1525 [CI Environment] Simplified env-setup script
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Labels: enhancement, [cat] pipelines

#1561 [Wiki] Update wiki dependencies with latest added resources
  docs/wiki/The CI environment - Pipeline design.md
Labels: documentation

#1560 [Wiki] CARML personas
  docs/wiki/Home.md
  docs/wiki/The context - Logical layers and personas.md
  docs/wiki/The context.md
  docs/wiki/media/Personas/ModuleDevelopers.png
  docs/wiki/media/Personas/SolutionConsumers.png
  docs/wiki/media/Personas/SolutionDevelopers.png
  docs/wiki/media/Personas/layers.png
Labels: documentation

#1483 [Modules] Congnitive Services: Set secure defaults
  .azuredevops/modulePipelines/ms.cognitiveservices.accounts.yml
  arm/Microsoft.CognitiveServices/accounts/.parameters/encr.parameters.json
  arm/Microsoft.CognitiveServices/accounts/.parameters/min.parameters.json
  arm/Microsoft.CognitiveServices/accounts/.parameters/parameters.json
  arm/Microsoft.CognitiveServices/accounts/.parameters/speech.parameters.json
  arm/Microsoft.CognitiveServices/accounts/deploy.bicep
  arm/Microsoft.CognitiveServices/accounts/readme.md
  utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/parameters.json
Labels: enhancement, [cat] modules

#1569 [Utilities] Added Format-Release function
  utilities/tools/Get-FormattedGitHubRelease.ps1
Labels: enhancement, [cat] organization

#1573 [Wiki] Sidebar and contribution flow update
  docs/wiki/Contribution guide - Contribution flow.md
  docs/wiki/_Sidebar.md
Labels: documentation

#1574 [Wiki] Contribution flow remove duplicate
  docs/wiki/Contribution guide - Contribution flow.md
Labels: documentation

#1571 [Modules] MongoDB: Removed throughput if database is deployed serverless
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
Labels: enhancement, [cat] modules

#1472 [Pipeline] Users/seseicht/adjust publish
  .azuredevops/pipelineTemplates/jobs.publishModule.yml
  .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
  .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  docs/wiki/Getting started - Scenario 2 Onboard module library and CI environment.md
  global.variables.yml
  utilities/pipelines/resourcePublish/Publish-ModuleToPrivateBicepRegistry.ps1
  utilities/pipelines/resourcePublish/Publish-ModuleToTemplateSpec.ps1
Labels: enhancement, [cat] pipelines, [cat] publishing

#1609 [Utilities] Added utility to bulk-run pipelines for a given branch
  .github/actions/templates/getWorkflowInput/action.yml
  docs/wiki/Contribution guide - Validate module locally.md
  docs/wiki/Contribution guide - Validate module on scale.md
  docs/wiki/Contribution guide.md
  utilities/pipelines/sharedScripts/Get-GitHubWorkflowDefaultInput.ps1
  utilities/tools/Invoke-PipelinesForBranch.ps1
Labels: enhancement

#1594 [Modules] MongoDB: Removed throughput if database is deployed serverless #1571
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
  arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
Labels: enhancement, [cat] modules

#1591 Updated implementation
  arm/Microsoft.Compute/diskEncryptionSets/.parameters/parameters.json
  arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
  arm/Microsoft.Compute/diskEncryptionSets/readme.md
Labels: enhancement, [cat] modules

#1615 [Fixes] Fix incorrect function reference for GitHub action
  .github/actions/templates/getWorkflowInput/action.yml
Labels: bug, [cat] pipelines

#1617 [Wiki] Reset some of the feedback from Wiki walkthrough
  docs/wiki/Solution creation.md
  docs/wiki/The CI environment - GitHub ReadMe module table update.md
  docs/wiki/The CI environment - Pipeline design.md
Labels: documentation, enhancement

#1618 [Modules] Minimum TLS version for SQL server
  modules/Microsoft.Sql/servers/.parameters/parameters.json
  modules/Microsoft.Sql/servers/deploy.bicep
  modules/Microsoft.Sql/servers/readme.md
Labels: enhancement, [cat] modules

#1568 [Modules] Added Web PubSub module
  .azuredevops/modulePipelines/ms.signalrservice.webpubsub.yml
  .github/workflows/ms.signalrservice.webpubsub.yml
  arm/Microsoft.SignalRService/webPubSub/.bicep/nested_rbac.bicep
  arm/Microsoft.SignalRService/webPubSub/.parameters/full.parameters.json
  arm/Microsoft.SignalRService/webPubSub/.parameters/min.parameters.json
  arm/Microsoft.SignalRService/webPubSub/deploy.bicep
  arm/Microsoft.SignalRService/webPubSub/readme.md
  arm/Microsoft.SignalRService/webPubSub/version.json
Labels: enhancement, [cat] modules

#1593 [Modules] AKS: Updated secure defaults
  .azuredevops/platformPipelines/platform.dependencies.yml
  .github/workflows/platform.dependencies.yml
  docs/wiki/The CI environment - Pipeline design.md
  modules/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
  modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
  modules/Microsoft.ContainerService/managedClusters/agentPools/readme.md
  modules/Microsoft.ContainerService/managedClusters/deploy.bicep
  modules/Microsoft.ContainerService/managedClusters/readme.md
  utilities/pipelines/dependencies/Microsoft.Compute/diskEncryptionSets/parameters/parameters.json
Labels: enhancement, [cat] modules

#1619 [Misc] Add automatic assignment to Pull-Requests
  .github/platform.auto-assign-PR.configuration.yml
  .github/workflows/platform.autoassign.yml
Labels: enhancement, [cat] pipelines, [cat] organization

#1623 [Modules] Recovery Services Vaults: Add private endpoint support with updated parameters file.
  modules/Microsoft.RecoveryServices/vaults/.parameters/parameters.json
  modules/Microsoft.RecoveryServices/vaults/deploy.bicep
  modules/Microsoft.RecoveryServices/vaults/readme.md
Labels: enhancement, [cat] modules
